<?php
declare(strict_types=1);
require_once __DIR__.'/_grammar.php';
require_once __DIR__.'/_handwriting.php';
require_once __DIR__.'/_precis_feedback.php';
require_once __DIR__.'/_mentor.php';
require_once __DIR__.'/_current_affairs.php';
require_once __DIR__.'/_mpt_core.php';
require_once __DIR__.'/_planner_core.php';
function cssv_planner_table(PDO $pdo,string $table): bool {$q=$pdo->prepare('SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=?');$q->execute([$table]);return (int)$q->fetchColumn()>0;}
function cssv_planner_settings(PDO $pdo,string $user,string $attempt): array {$q=$pdo->prepare('SELECT version,religion_choice,imported_at FROM attempt_planner_settings WHERE attempt_id=? AND user_id=?');$q->execute([$attempt,$user]);$r=$q->fetch();return ['version'=>(int)($r['version']??0),'religion_choice'=>$r['religion_choice']??null,'imported_at'=>isset($r['imported_at'])?cssv_pro_iso($r['imported_at']):null];}
function cssv_planner_progress(PDO $pdo,string $user,string $attempt): array {$q=$pdo->prepare('SELECT * FROM attempt_unit_progress WHERE attempt_id=? AND user_id=?');$q->execute([$attempt,$user]);$out=[];foreach($q->fetchAll() as $r){foreach(['version','review_count'] as $k)$r[$k]=(int)$r[$k];$r['source']=json_decode($r['source'],true,32,JSON_THROW_ON_ERROR);$out[$r['unit_id']]=$r;}return $out;}
function cssv_planner_tasks(PDO $pdo,string $user,string $plan): array {$q=$pdo->prepare('SELECT * FROM attempt_plan_tasks WHERE plan_id=? AND user_id=? ORDER BY created_at,id');$q->execute([$plan,$user]);$rows=$q->fetchAll();foreach($rows as &$r){foreach(['version','minutes','actual_minutes'] as $k)$r[$k]=(int)$r[$k];$r['snapshot']=json_decode($r['snapshot'],true,32,JSON_THROW_ON_ERROR);}unset($r);usort($rows,fn($a,$b)=>(in_array($a['status'],['pending','partial'],true)?0:1)<=>(in_array($b['status'],['pending','partial'],true)?0:1)?:((int)($b['snapshot']['priority']??0)<=>(int)($a['snapshot']['priority']??0))?:strcmp($a['created_at'].'/'.$a['id'],$b['created_at'].'/'.$b['id']));return $rows;}
function cssv_planner_plan(PDO $pdo,string $user,string $attempt,string $date): ?array {$q=$pdo->prepare('SELECT * FROM attempt_daily_plans WHERE attempt_id=? AND user_id=? AND plan_date=?');$q->execute([$attempt,$user,$date]);$r=$q->fetch();if(!$r)return null;foreach(['version','budget'] as $k)$r[$k]=(int)$r[$k];$r['summary']=json_decode($r['summary'],true,32,JSON_THROW_ON_ERROR);$r['tasks']=cssv_planner_tasks($pdo,$user,$r['id']);return $r;}
function cssv_planner_link_source(PDO $pdo,string $user,string $attempt,string $kind,string $source,?array $unit): array {
 if($kind==='mentor'){$a=cssv_mentor_answer($pdo,cssv_pro_id($source),$user);if($a['attempt_id']!==$attempt||!$unit||$a['subject_id']!==$unit['subject_id'])throw new OutOfBoundsException('Choose your own answer from the same attempt and subject.');return ['title'=>$a['topic'],'date'=>$a['written_date'],'source_id'=>$a['id'],'to'=>'/account/answer-performance?id='.$a['id'],'basis'=>'Student-entered human mentor record. Current marks are read from its evaluation history.'];}
 if($kind==='mcq'){$q=$pdo->prepare('SELECT question_id,category,topic,correct,attempted_at FROM question_attempts WHERE user_id=? AND question_id=? ORDER BY attempted_at,id LIMIT 1');$q->execute([$user,$source]);$r=$q->fetch();if(!$r)throw new OutOfBoundsException('Recorded question not found.');if(!in_array((int)$r['correct'],[0,1],true))throw new OutOfBoundsException('Recorded response is unavailable.');return ['title'=>$r['topic']?:$r['category'],'question_id'=>$r['question_id'],'correct'=>(int)$r['correct'],'total'=>1,'date'=>cssv_planner_day(new DateTimeImmutable($r['attempted_at'],new DateTimeZone('UTC'))),'to'=>'/gk/quiz','basis'=>'First recorded response to this distinct question in synced self-practice. Not an authenticated examination result.'];}
 if($kind==='test'){if(!preg_match('/^[1-9][0-9]{0,19}$/D',$source))throw new InvalidArgumentException('Choose a recorded test identifier.');$q=$pdo->prepare('SELECT id,category,score,total,completed_at,metadata FROM quiz_attempts WHERE user_id=? AND id=?');$q->execute([$user,$source]);$r=$q->fetch();if(!$r||(string)$r['id']!==$source)throw new OutOfBoundsException('Recorded practice test not found.');if((int)$r['total']<=0||(int)$r['score']<0||(int)$r['score']>(int)$r['total'])throw new OutOfBoundsException('Recorded practice points are unavailable.');$meta=json_decode($r['metadata']?:'{}',true);if(($meta['mock_kind']??null)==='mpt')throw new InvalidArgumentException('Legacy browser MPT results are not counted as native mock results.');return ['title'=>$r['category'],'score'=>(int)$r['score'],'total'=>(int)$r['total'],'date'=>cssv_planner_day(new DateTimeImmutable($r['completed_at'],new DateTimeZone('UTC'))),'to'=>'/gk/quiz','basis'=>'Recorded synced practice test, not an authenticated official examination.'];}
 if($kind==='mpt'){
  if(!cssv_planner_table($pdo,'mpt_attempts'))throw new OutOfBoundsException('Native MPT records are unavailable.');
  $q=$pdo->prepare("SELECT t.id,t.score,t.total_marks,t.submitted_at,t.attempt_no,m.title,m.status,m.exam_end_at,m.results_release_policy,m.results_delay_minutes,a.application_code,a.status application_status FROM mpt_attempts t JOIN mpt_mocks m ON m.id=t.mock_id JOIN mpt_applications a ON a.id=t.application_id AND a.mock_id=t.mock_id WHERE t.user_id=? AND a.user_id=? AND t.id=? AND t.status IN ('SUBMITTED','AUTO_SUBMITTED') AND t.voided_at IS NULL");$q->execute([$user,$user,cssv_pro_id($source)]);$r=$q->fetch();
  return cssv_planner_mpt_snapshot($r?:null);
 }
 if($kind==='past_paper'){
  if(!$unit||$unit['paper_count']===0)throw new InvalidArgumentException('Choose a unit with mapped source-derived papers.');$path=dirname(__DIR__).'/css-past-paper-analysis/'.$unit['subject_id'].'.json';if(!is_file($path))throw new OutOfBoundsException('Paper source unavailable.');$data=json_decode((string)file_get_contents($path),true,64,JSON_THROW_ON_ERROR);$index=(int)substr($unit['id'],strrpos($unit['id'],':')+1);
  foreach($data['sections'] as $section)foreach($section['topics'] as $topic)if($topic['syllabusSectionIndex']===$index)foreach($topic['questions'] as $q)if($q['id']===$source)return ['title'=>$q['text'],'year'=>$q['year'],'paper'=>$q['paper'],'date'=>cssv_planner_day(),'to'=>$unit['paper_to'],'basis'=>'Self-reported review of an existing source-derived question. Repository mappings are not independently reverified here.'];throw new OutOfBoundsException('Choose a question mapped to this selected unit.');
 }
 throw new InvalidArgumentException('Choose MCQ, practice test, native MPT, paper review or human answer evidence.');
}
function cssv_planner_mpt_snapshot(?array $r): array {
  if(!$r||$r['status']!=='PUBLISHED'||$r['application_status']!=='ACTIVE'||$r['score']===null||$r['total_marks']===null||(float)$r['total_marks']<=0||mpt_now_for_planner()<mpt_result_release_at($r,(int)mpt_ms($r['submitted_at']),(int)mpt_ms($r['exam_end_at'])))throw new OutOfBoundsException('An owned, released native MPT result is required.');
  return ['title'=>$r['title'],'score'=>(float)$r['score'],'total'=>(float)$r['total_marks'],'attempt_no'=>(int)$r['attempt_no'],'date'=>cssv_planner_day(new DateTimeImmutable($r['submitted_at'],new DateTimeZone('UTC'))),'to'=>'/account/mpt/results/'.$r['application_code'],'basis'=>'Released native CSS Vista MPT mock result. Repeated attempts remain separate.'];
}
function mpt_now_for_planner(): int {return (int)floor(microtime(true)*1000);}
function cssv_planner_links(PDO $pdo,string $user,string $attempt): array {
 $q=$pdo->prepare('SELECT * FROM attempt_evidence_links WHERE attempt_id=? AND user_id=? ORDER BY created_at,evidence_key');$q->execute([$attempt,$user]);$rows=$q->fetchAll();$q=$pdo->prepare(cssv_mentor_select().' WHERE a.user_id=? AND a.attempt_id=? AND EXISTS (SELECT 1 FROM attempt_evidence_links l WHERE l.attempt_id=a.attempt_id AND l.user_id=a.user_id AND l.kind=\'mentor\' AND l.source_id=a.id)');$q->execute([$user,$attempt]);$answers=array_column(array_map('cssv_mentor_normalize',$q->fetchAll()),null,'id');$mpt=[];if(cssv_planner_table($pdo,'mpt_attempts')){$q=$pdo->prepare("SELECT t.id,t.score,t.total_marks,t.submitted_at,t.attempt_no,m.title,m.status,m.exam_end_at,m.results_release_policy,m.results_delay_minutes,a.application_code,a.status application_status FROM mpt_attempts t JOIN mpt_mocks m ON m.id=t.mock_id JOIN mpt_applications a ON a.id=t.application_id AND a.mock_id=t.mock_id JOIN attempt_evidence_links l ON l.source_id=t.id AND l.kind='mpt' AND l.user_id=t.user_id WHERE t.user_id=? AND a.user_id=? AND l.attempt_id=? AND t.status IN ('SUBMITTED','AUTO_SUBMITTED') AND t.voided_at IS NULL");$q->execute([$user,$user,$attempt]);$mpt=array_column($q->fetchAll(),null,'id');}foreach($rows as &$r){$r['snapshot']=json_decode($r['snapshot'],true,32,JSON_THROW_ON_ERROR);if($r['kind']==='mentor'){$r['answer']=$answers[$r['source_id']]??['status'=>'not_attempted'];}if($r['kind']==='mpt'){try{$r['current']=cssv_planner_mpt_snapshot($mpt[$r['source_id']]??null);$r['eligible']=true;}catch(OutOfBoundsException){$r['eligible']=false;}}}unset($r);return $rows;
}
function cssv_planner_sources(PDO $pdo,string $user,string $attempt,string $kind,?array $unit=null,int $offset=0): array {
 if($kind==='mentor'){$q=$pdo->prepare('SELECT id source_id,topic title,status FROM mentor_answers WHERE user_id=? AND attempt_id=?'.($unit?' AND subject_id=?':'').' ORDER BY created_at DESC,id LIMIT 51 OFFSET '.$offset);$q->execute($unit?[$user,$attempt,$unit['subject_id']]:[$user,$attempt]);$rows=$q->fetchAll();}
 elseif($kind==='mcq'){$q=$pdo->prepare('SELECT question_id source_id,COALESCE(MAX(NULLIF(topic,\'\')),MAX(category)) title FROM question_attempts WHERE user_id=? GROUP BY question_id ORDER BY MAX(attempted_at) DESC,question_id LIMIT 51 OFFSET '.$offset);$q->execute([$user]);$rows=$q->fetchAll();}
 elseif($kind==='test'){$q=$pdo->prepare("SELECT id source_id,category title FROM quiz_attempts WHERE user_id=? AND COALESCE(JSON_UNQUOTE(JSON_EXTRACT(metadata,'$.mock_kind')),'')<>'mpt' ORDER BY completed_at DESC,id LIMIT 51 OFFSET ".$offset);$q->execute([$user]);$rows=$q->fetchAll();}
 elseif($kind==='mpt'){$rows=[];if(cssv_planner_table($pdo,'mpt_attempts')){$q=$pdo->prepare("SELECT id source_id FROM mpt_attempts WHERE user_id=? AND status IN ('SUBMITTED','AUTO_SUBMITTED') AND voided_at IS NULL ORDER BY submitted_at DESC,id LIMIT 51 OFFSET ".$offset);$q->execute([$user]);$raw=$q->fetchAll();$rawMore=count($raw)>50;foreach(array_slice($raw,0,50) as $r){try{$snapshot=cssv_planner_link_source($pdo,$user,$attempt,'mpt',$r['source_id'],null);$rows[]=['source_id'=>$r['source_id'],'title'=>$snapshot['title']];}catch(OutOfBoundsException){}}}}
 elseif($kind==='past_paper'){$rows=[];if($unit&&$unit['paper_count']>0){$path=dirname(__DIR__).'/css-past-paper-analysis/'.$unit['subject_id'].'.json';$data=json_decode((string)file_get_contents($path),true,64,JSON_THROW_ON_ERROR);$index=(int)substr($unit['id'],strrpos($unit['id'],':')+1);foreach($data['sections'] as $section)foreach($section['topics'] as $topic)if($topic['syllabusSectionIndex']===$index)foreach($topic['questions'] as $q)$rows[]=['source_id'=>$q['id'],'title'=>$q['year'].' · '.$q['text']];$rows=array_slice($rows,$offset,51);}}
 else throw new InvalidArgumentException('Choose an evidence type.');return ['records'=>array_slice($rows,0,50),'has_more'=>isset($rawMore)?$rawMore:count($rows)>50];
}
