<?php
declare(strict_types=1);
require_once __DIR__.'/_planner_sources.php';
require_once __DIR__.'/_planner_schema.php';
function cssv_planner_ensure(PDO $pdo): void {
 static $ready=false;if($ready)return;cssv_grammar_ensure($pdo);cssv_handwriting_ensure($pdo);cssv_precis_feedback_ensure($pdo);cssv_mentor_ensure($pdo);ca_ensure_schema($pdo);
 if((int)$pdo->query("SELECT GET_LOCK('cssvista-attempt-planner-v1',5)")->fetchColumn()!==1)throw new RuntimeException('planner_schema_busy');
 try{foreach(cssv_planner_schema_statements() as $sql)$pdo->exec($sql);$ready=true;}finally{$pdo->query("SELECT RELEASE_LOCK('cssvista-attempt-planner-v1')");}
}
function cssv_planner_event(PDO $pdo,string $user,string $attempt,string $type,array $payload,?string $task=null,?string $unit=null): void {$pdo->prepare('INSERT INTO attempt_planner_events(id,user_id,attempt_id,event_type,payload,task_id,unit_id) VALUES(?,?,?,?,?,?,?)')->execute([cssv_uuid_v4(),$user,$attempt,$type,json_encode($payload,JSON_THROW_ON_ERROR),$task,$unit]);}
function cssv_planner_context(PDO $pdo,string $user,string $attempt,string $today): array {
 $a=cssv_learning_attempt($pdo,$attempt,$user);$settings=cssv_planner_settings($pdo,$user,$attempt);$units=cssv_planner_selected($a,$settings['religion_choice']);$progress=cssv_planner_progress($pdo,$user,$attempt);$links=cssv_planner_links($pdo,$user,$attempt);
 $grammar=cssv_grammar_read($pdo,$user,$attempt);$precis=cssv_precis_progress($pdo,$user,$attempt);$writingProfile=cssv_precis_feedback_profile($pdo,$user,$attempt);
 $q=$pdo->prepare(cssv_mentor_select()." WHERE a.user_id=? AND a.attempt_id=? ORDER BY CASE WHEN a.status='evaluated' AND e.obtained_marks/e.maximum_marks<? THEN 0 WHEN a.status='awaiting_evaluation' THEN 1 WHEN a.status='not_attempted' THEN 2 ELSE 3 END,a.created_at,a.id LIMIT 200");$q->execute([$user,$attempt,cssv_planner_rules()['mentor_review_below']/100]);$mentor=array_map('cssv_mentor_normalize',$q->fetchAll());
 $q=$pdo->prepare('SELECT i.id,i.headline,i.publication_date FROM current_affairs_items i JOIN current_affairs_days d ON d.publication_date=i.publication_date LEFT JOIN current_affairs_user_items u ON u.item_id=i.id AND u.user_id=? WHERE '.ca_visible()." AND COALESCE(u.status,'unread')<>'read' AND NOT EXISTS (SELECT 1 FROM attempt_evidence_links l WHERE l.user_id=? AND l.attempt_id=? AND l.kind='current_affairs' AND l.source_id=i.id) ORDER BY i.publication_date DESC,i.id LIMIT 1");$q->execute([$user,$user,$attempt]);$affair=$q->fetch()?:null;
 $q=$pdo->prepare('SELECT t.*,p.plan_date FROM attempt_plan_tasks t JOIN attempt_daily_plans p ON p.id=t.plan_id WHERE p.user_id=? AND p.attempt_id=? AND p.plan_date<? AND t.status IN (\'pending\',\'partial\') ORDER BY p.plan_date,t.id LIMIT 100');$q->execute([$user,$attempt,$today]);$overdue=$q->fetchAll();foreach($overdue as &$r){$r['snapshot']=json_decode($r['snapshot'],true,32,JSON_THROW_ON_ERROR);foreach(['minutes','actual_minutes','version'] as $k)$r[$k]=(int)$r[$k];}unset($r);
 $subjects=array_unique(array_column($units,'subject_id'));$placeholders=implode(',',array_fill(0,count($subjects),'?'));$q=$pdo->prepare('SELECT a.subject_id,a.topic,(a.sequence>1) is_retry,COUNT(*) count,SUM(e.obtained_marks) obtained,SUM(e.maximum_marks) maximum FROM mentor_answers a JOIN mentor_evaluations e ON e.answer_id=a.id AND e.revision=a.evaluation_revision WHERE a.user_id=? AND a.attempt_id=? AND a.subject_id IN ('.$placeholders.') GROUP BY a.subject_id,a.topic,(a.sequence>1)');$q->execute([$user,$attempt,...$subjects]);$mentorSummary=cssv_mentor_summary($q->fetchAll());
 return ['mentor_summary'=>$mentorSummary,'attempt'=>$a,'settings'=>$settings,'units'=>$units,'progress'=>$progress,'links'=>$links,'grammar'=>$grammar,'precis'=>$precis,'precis_writing'=>$writingProfile,'mentor'=>$mentor,'affair'=>$affair,'overdue'=>$overdue,'active'=>cssv_pro_membership($pdo,$user)['status']==='active'];
}
function cssv_planner_candidate(string $key,string $kind,string $lane,string $subject,string $title,string $why,string $to,int $priority,?string $unit=null,array $extra=[]): array {
 return ['work_key'=>$key,'kind'=>$kind,'lane'=>$lane,'subject'=>$subject,'title'=>$title,'why'=>$why,'to'=>$to,'priority'=>$priority,'unit_id'=>$unit,'minutes'=>cssv_planner_rules()['minutes'][$kind],...$extra];
}
function cssv_planner_candidates(array $c,string $today): array {
 $out=[];$attempt=$c['attempt']['id'];$subjectCoverage=[];foreach($c['units'] as $u){$subjectCoverage[$u['subject_id']]??=['covered'=>0,'total'=>0];$subjectCoverage[$u['subject_id']]['total']++;if(!cssv_planner_source_changed($u,$c['progress'][$u['id']]??[])&&($c['progress'][$u['id']]['coverage']??'')==='covered')$subjectCoverage[$u['subject_id']]['covered']++;}
 foreach($c['units'] as $u){$r=$c['progress'][$u['id']]??[];if(cssv_planner_source_changed($u,$r))continue;$covered=($r['coverage']??'')==='covered';if($covered&&isset($r['next_revision'])&&$r['next_revision']<=$today)$out[]=cssv_planner_candidate('revision:'.$u['id'].':'.$r['next_revision'],'revision','revision',$u['subject'],'Recall '.$u['title'],'Your reported study/review schedule is due on '.$r['next_revision'].'.',$u['to'],100,$u['id']);
  elseif(!$covered){$s=$subjectCoverage[$u['subject_id']];$priority=40-(int)floor(10*$s['covered']/$s['total'])+(($r['coverage']??'')==='learning'?5:0);$out[]=cssv_planner_candidate('learn:'.$u['id'],'learn','coverage',$u['subject'],'Study '.$u['title'],($r['coverage']??'')==='learning'?'This selected unit is partly covered. Continue the remaining material.':'This selected study unit has not been reported covered.',$u['to'],$priority,$u['id']);}
  elseif($u['paper_count']>0&&!count(array_filter($c['links'],fn($l)=>$l['unit_id']===$u['id']&&$l['kind']==='past_paper')))$out[]=cssv_planner_candidate('past_paper:'.$u['id'],'past_paper','papers',$u['subject'],'Review papers for '.$u['title'],$u['paper_count'].' source-derived question appearances are mapped to this section. Recurrence is not a prediction.',$u['paper_to'],50,$u['id']);
 }
 foreach($c['grammar']['profile']['items'] as $g){if($g['due']||$g['state']==='Needs review')$out[]=cssv_planner_candidate('grammar:'.$g['day'],'grammar','grammar','English & Grammar','Review '.$g['title'],$g['due']?($g['due'].' authored questions are due under your existing Grammar schedule.'):'Actual practice or writing findings show this lesson needs review.','/grammar-course?view=lab&day='.$g['day'].'&attempt='.$attempt,95,null,['grammar_day'=>$g['day']]);}
 $day=(int)($c['grammar']['state']['currentDay']??1);if(!$out||!count(array_filter($out,fn($x)=>$x['kind']==='grammar'))){$completed=$c['grammar']['state']['completed']??[];$next=null;for($i=1;$i<=30;$i++)if(!in_array($i,$completed,true)){$next=$i;break;}$day=$next??$day;$g=cssv_grammar_catalog()[$day-1];$out[]=cssv_planner_candidate('grammar:'.$day,'grammar','grammar','English & Grammar',($next?'Continue ':'Maintain ').$g['title'],$next?'Continue the next uncompleted authored lesson.':'All course days are reported complete; maintenance continues without a mastery claim.','/grammar-course?day='.$day.'&attempt='.$attempt,55);}
 if($c['active']){$p=$c['precis'];$due=array_sum(array_map(fn($s)=>count($s['review_ids']),$p['profile']['items']));$weak=count(array_filter($c['precis_writing']['items'],fn($s)=>$s['state']==='Weak'));$out[]=cssv_planner_candidate('precis:'.$p['current_day'],'precis','precis','Précis','Continue Précis day '.$p['current_day'],$due?($due.' recognition drills need review.'):($weak?'Source-bound writing findings identify skills for revision.':'Continue your saved handbook position and practise independently.'),'/account/precis?attempt='.$attempt.'&view='.($due?'review':'course').'&day='.$p['current_day'],($due||$weak)?85:50,null,['requires_pro'=>true]);}
 $subjects=array_unique(array_column($c['units'],'subject_id'));
 foreach($c['mentor'] as $m){if(!in_array($m['subject_id'],$subjects,true))continue;
  $why=$m['status']==='not_attempted'?'This saved practice question has not been marked written.':($m['status']==='awaiting_evaluation'?'Your written answer awaits a human mentor result.':(($m['percentage']<cssv_planner_rules()['mentor_review_below'])?'The current student-entered human mentor percentage is below the '.cssv_planner_rules()['mentor_review_below'].'% study-review threshold.':'Review the human mentor feedback and continue independent practice.'));
  if($m['status']==='evaluated'&&$m['percentage']>=cssv_planner_rules()['mentor_review_below'])continue;
  $out[]=cssv_planner_candidate('mentor:'.$m['id'].':'.$m['evaluation_revision'],'mentor','writing',$m['subject_id'],($m['status']==='not_attempted'?'Write: ':($m['status']==='awaiting_evaluation'?'Record human feedback: ':'Review mentor feedback: ')).$m['topic'],$why,'/account/answer-performance?id='.$m['id'],90,null,['answer_id'=>$m['id']]);
 }
 if(!count(array_filter($out,fn($x)=>$x['lane']==='writing')))$out[]=cssv_planner_candidate('writing:paragraph','writing','writing','English expression','Write one original paragraph','Practise independently; saving writing requires no AI evaluation.','/account/expression?attempt='.$attempt,45);
 if($c['affair']){$s=$c['affair'];$out[]=cssv_planner_candidate('current_affairs:'.$s['id'],'current_affairs','affairs','Current Affairs',$s['headline'],'Read the published development dated '.$s['publication_date'].'. This is stored material, not live news verification.','/account/current-affairs/'.rawurlencode($s['id']),50,null,['story_id'=>$s['id'],'edition_date'=>$s['publication_date']]);}
 foreach($c['overdue'] as $old){if($old['unit_id']&&(!isset($c['units'][$old['unit_id']])||cssv_planner_source_changed($c['units'][$old['unit_id']],$c['progress'][$old['unit_id']]??[])))continue;$s=$old['snapshot'];$out[]=[...$s,'work_key'=>$old['work_key'],'kind'=>$old['kind'],'unit_id'=>$old['unit_id'],'minutes'=>$old['minutes']-$old['actual_minutes'],'priority'=>in_array($old['kind'],['revision','grammar','mentor'],true)?105:42,'why'=>'Unfinished work from '.$old['plan_date'].'. Carry only the remaining block; prior work stays recorded.','carry_id'=>$old['id'],'carry_version'=>$old['version']];}
 if($c['attempt']['stage']==='revision')foreach($out as &$candidate)if(in_array($candidate['kind'],['revision','past_paper','mentor','grammar','precis'],true))$candidate['priority']+=10;unset($candidate);
 return $out;
}
function cssv_planner_proposal(PDO $pdo,string $user,string $attempt,string $today,?array $context=null): array {
 $c=$context??cssv_planner_context($pdo,$user,$attempt,$today);$plan=cssv_planner_plan($pdo,$user,$attempt,$today);$selection=cssv_planner_allocate(cssv_planner_candidates($c,$today),$c['attempt']['daily_minutes'],$plan['tasks']??[],$today);
 if(!$c['settings']['religion_choice'])$selection=['tasks'=>[],'locked'=>[],'allocated_minutes'=>0,'remaining_minutes'=>$c['attempt']['daily_minutes'],'recorded_over_budget_minutes'=>0];
 $summary=cssv_planner_capacity($c['attempt'],$c['units'],$c['progress'],$today);
 $basis=['day'=>$today,'rule'=>cssv_planner_rules(),'attempt'=>$c['attempt'],'settings'=>$c['settings'],'progress'=>$c['progress'],'units_hash'=>cssv_planner_hash($c['units']),'grammar'=>$c['grammar']['profile'],'precis'=>$c['precis'],'precis_writing'=>$c['precis_writing'],'links'=>$c['links'],'mentor'=>$c['mentor'],'affair'=>$c['affair'],'overdue'=>$c['overdue'],'selected'=>$selection,'plan_version'=>$plan['version']??0];
 $pending=array_filter($plan['tasks']??[],fn($t)=>$t['status']==='pending');$wanted=array_map(fn($t)=>[$t['work_key'],$t['minutes']],$selection['tasks']);$existing=array_map(fn($t)=>[$t['work_key'],$t['minutes']],array_values($pending));sort($wanted);sort($existing);
 return ['date'=>$today,'expected_version'=>$plan['version']??0,'hash'=>cssv_planner_hash($basis),'budget'=>$c['attempt']['daily_minutes'],'rule_version'=>cssv_planner_rules()['version'],'summary'=>$summary,'selection'=>$selection,'has_changes'=>!$plan||$wanted!==$existing||$plan['budget']!==$c['attempt']['daily_minutes'],'requires_setup'=>!$c['settings']['religion_choice']];
}
