<?php
declare(strict_types=1);
function cssv_planner_percentage(float|int $numerator,float|int $denominator): ?float {return $denominator>0?round(100*$numerator/$denominator,1):null;}
function cssv_planner_dimensions(array $c,string $today): array {
 $capacity=cssv_planner_capacity($c['attempt'],$c['units'],$c['progress'],$today);$mcq=['correct'=>0,'total'=>0];$tests=['score'=>0,'total'=>0,'count'=>0];$mptFirst=$tests;$mptRepeat=$tests;$paperUnits=[];$scheduled=0;$due=0;$readings=0;$unitLinks=[];
 foreach($c['progress'] as $id=>$r)if(isset($c['units'][$id])&&!cssv_planner_source_changed($c['units'][$id],$r)&&$r['coverage']==='covered'&&$r['next_revision']){$scheduled++;if($r['next_revision']<=$today)$due++;}
 foreach($c['links'] as $l){if($l['unit_id']!==null&&(!isset($c['units'][$l['unit_id']])||cssv_planner_source_changed($c['units'][$l['unit_id']],$c['progress'][$l['unit_id']]??[])))continue;$s=$l['snapshot'];$unitLinks[$l['unit_id']??''][]=$l;
  if($l['kind']==='mcq'){$mcq['correct']+=$s['correct'];$mcq['total']++;}
  elseif($l['kind']==='test'){$tests['score']+=$s['score'];$tests['total']+=$s['total'];$tests['count']++;}
  elseif($l['kind']==='mpt'&&($l['eligible']??false)){$s=$l['current'];$key=$s['attempt_no']===1?'mptFirst':'mptRepeat';${$key}['score']+=$s['score'];${$key}['total']+=$s['total'];${$key}['count']++;}
  elseif($l['kind']==='past_paper')$paperUnits[$l['unit_id']]=true;
  elseif($l['kind']==='current_affairs')$readings++;
 }
 $mentor=[...$c['mentor_summary'],'review_threshold'=>cssv_planner_rules()['mentor_review_below']];
 $g=$c['grammar']['profile']['totals'];$recognitionQuestions=0;$recognitionCorrect=0;foreach($c['precis']['profile']['items'] as $s){$recognitionQuestions+=$s['questions'];$recognitionCorrect+=$s['first_correct'];}
 $matrix=[];foreach($c['units'] as $u){$r=$c['progress'][$u['id']]??[];$sourceChanged=cssv_planner_source_changed($u,$r);$links=$unitLinks[$u['id']]??[];$by=array_count_values(array_column($links,'kind'));$written=0;$evaluated=0;foreach($links as $l)if($l['kind']==='mentor'){if($l['answer']['status']!=='not_attempted')$written++;if($l['answer']['status']==='evaluated')$evaluated++;}
  $matrix[$u['id']]=[...$u,'source_changed'=>$sourceChanged,'version'=>$r['version']??0,'coverage'=>$r['coverage']??'not_started','last_studied'=>$r['last_studied']??null,'next_revision'=>$r['next_revision']??null,'review_count'=>$r['review_count']??0,'mcq_count'=>$by['mcq']??0,'paper_reviews'=>$by['past_paper']??0,'written_answers'=>$written,'mentor_evaluated'=>$evaluated,'tests'=>$by['test']??0,'imported_states'=>$r['source']['legacy_states']??null];
 }
 $paperDenominator=count(array_filter($c['units'],fn($u)=>$u['paper_count']>0));
 return ['matrix'=>$matrix,'coverage'=>$capacity,'revision'=>['scheduled'=>$scheduled,'due'=>$due,'current_percentage'=>cssv_planner_percentage($scheduled-$due,$scheduled),'basis'=>'Covered units with an explicit review date. Unknown earlier study dates receive a first review due today. This is schedule health, not mastery.'],'mcq'=>[...$mcq,'percentage'=>cssv_planner_percentage($mcq['correct'],$mcq['total']),'basis'=>'First responses to explicitly linked distinct questions. Synced self-practice, not an examination result; retries do not increase this percentage.'],'past_papers'=>['reviewed_units'=>count($paperUnits),'mapped_units'=>$paperDenominator,'percentage'=>cssv_planner_percentage(count($paperUnits),$paperDenominator),'basis'=>'Self-reported review in explicitly mapped repository sections; the denominator excludes units without mapped questions. Not a readiness guarantee.'],'tests'=>[...$tests,'percentage'=>cssv_planner_percentage($tests['score'],$tests['total']),'basis'=>'Explicitly linked recorded practice tests. Sum of obtained / sum of available points, not a mean of test percentages. Legacy browser MPT results excluded.'],'mpt'=>['first'=>[...$mptFirst,'percentage'=>cssv_planner_percentage($mptFirst['score'],$mptFirst['total'])],'repeats'=>[...$mptRepeat,'percentage'=>cssv_planner_percentage($mptRepeat['score'],$mptRepeat['total'])],'basis'=>'Only explicitly linked owned released, active and non-void native MPT results. First and repeated attempts separate; original result dates preserved.'],'mentor'=>$mentor,'grammar'=>['questions'=>$g['questions'],'correct'=>$g['correct'],'percentage'=>cssv_planner_percentage($g['correct'],$g['questions']),'due'=>$g['due'],'completed_days'=>$g['completed'],'basis'=>$c['grammar']['profile']['basis']],'precis'=>['recognition_questions'=>$recognitionQuestions,'recognition_correct'=>$recognitionCorrect,'recognition_percentage'=>cssv_planner_percentage($recognitionCorrect,$recognitionQuestions),'completed_days'=>count($c['precis']['completed']),'recognition'=>$c['precis']['profile'],'writing'=>$c['precis_writing'],'basis'=>'Recognition accuracy and source-bound independent writing evidence are separate; course completion does not imply assessed writing ability.'],'current_affairs'=>['reading_declarations'=>$readings,'basis'=>'Distinct dated developments reported read through this attempt’s plan; reading is not a comprehension assessment.'],'overall_percentage'=>null,'basis'=>'Different preparation evidence dimensions are displayed separately. An unavailable assessment receives no full-credit substitute and is not averaged into an invented readiness score.'];
}
function cssv_planner_period(PDO $pdo,string $user,string $attempt,string $start,string $end,array $c): array {
 $from=(new DateTimeImmutable($start.' 00:00:00',new DateTimeZone('Asia/Karachi')))->setTimezone(new DateTimeZone('UTC'))->format('Y-m-d H:i:s');$until=(new DateTimeImmutable(cssv_planner_add_days($end,1).' 00:00:00',new DateTimeZone('Asia/Karachi')))->setTimezone(new DateTimeZone('UTC'))->format('Y-m-d H:i:s');
 $q=$pdo->prepare("SELECT SUM(CASE WHEN event_type='task_work' THEN CAST(JSON_UNQUOTE(JSON_EXTRACT(payload,'$.delta_minutes')) AS UNSIGNED) ELSE 0 END) minutes,SUM(event_type='task_work' AND JSON_UNQUOTE(JSON_EXTRACT(payload,'$.status'))='completed') completed,SUM(event_type='task_work' AND JSON_UNQUOTE(JSON_EXTRACT(payload,'$.status'))='skipped') skipped,SUM(event_type='task_move') moved,SUM(event_type='coverage_save') coverage_declarations,SUM(event_type='coverage_import') imports FROM attempt_planner_events WHERE user_id=? AND attempt_id=? AND occurred_at>=? AND occurred_at<?");$q->execute([$user,$attempt,$from,$until]);$r=$q->fetch();foreach($r as &$v)$v=(int)$v;unset($v);
 $q=$pdo->prepare("SELECT COUNT(DISTINCT unit_id) units FROM attempt_planner_events WHERE user_id=? AND attempt_id=? AND occurred_at>=? AND occurred_at<? AND event_type='task_work' AND JSON_UNQUOTE(JSON_EXTRACT(payload,'$.status'))='completed' AND JSON_UNQUOTE(JSON_EXTRACT(payload,'$.kind'))='learn'");$q->execute([$user,$attempt,$from,$until]);$r['studied_units']=(int)$q->fetchColumn();$q=$pdo->prepare("SELECT JSON_UNQUOTE(JSON_EXTRACT(payload,'$.kind')) kind,COUNT(*) blocks FROM attempt_planner_events WHERE user_id=? AND attempt_id=? AND occurred_at>=? AND occurred_at<? AND event_type='task_work' AND JSON_UNQUOTE(JSON_EXTRACT(payload,'$.status'))='completed' GROUP BY kind");$q->execute([$user,$attempt,$from,$until]);$r['completed_blocks']=array_column($q->fetchAll(),'blocks','kind');
 $q=$pdo->prepare('SELECT SUM(v.version=1) first_drafts,SUM(v.version>1) rewrites FROM writing_versions v JOIN writing_records w ON w.id=v.writing_id WHERE w.user_id=? AND w.attempt_id=? AND v.created_at>=? AND v.created_at<?');$q->execute([$user,$attempt,$from,$until]);$w=$q->fetch();$r['first_drafts']=(int)$w['first_drafts'];$r['rewrites']=(int)$w['rewrites'];
 $q=$pdo->prepare('SELECT a.subject_id,a.topic,(a.sequence>1) is_retry,COUNT(*) count,SUM(e.obtained_marks) obtained,SUM(e.maximum_marks) maximum FROM mentor_answers a JOIN mentor_evaluations e ON e.answer_id=a.id AND e.revision=a.evaluation_revision WHERE a.user_id=? AND a.attempt_id=? AND e.evaluation_date>=? AND e.evaluation_date<=? GROUP BY a.subject_id,a.topic,(a.sequence>1)');$q->execute([$user,$attempt,$start,$end]);$r['mentor']=cssv_mentor_summary($q->fetchAll());
 $r['mcq_correct']=0;$r['mcq_questions']=0;$r['test_score']=0;$r['test_total']=0;$r['paper_reviews']=0;$r['current_affairs_readings']=0;$r['mpt_first_score']=0;$r['mpt_first_total']=0;$r['mpt_repeat_score']=0;$r['mpt_repeat_total']=0;
 foreach($c['links'] as $l){$s=$l['snapshot'];$day=$s['date']??null;if(!$day||$day<$start||$day>$end)continue;if($l['kind']==='mcq'){$r['mcq_questions']++;$r['mcq_correct']+=$s['correct'];}elseif($l['kind']==='test'){$r['test_score']+=$s['score'];$r['test_total']+=$s['total'];}elseif($l['kind']==='past_paper')$r['paper_reviews']++;elseif($l['kind']==='current_affairs')$r['current_affairs_readings']++;elseif($l['kind']==='mpt'&&($l['eligible']??false)){$s=$l['current'];$prefix=$s['attempt_no']===1?'mpt_first':'mpt_repeat';$r[$prefix.'_score']+=$s['score'];$r[$prefix.'_total']+=$s['total'];}}
 $r['mcq_percentage']=cssv_planner_percentage($r['mcq_correct'],$r['mcq_questions']);$r['test_percentage']=cssv_planner_percentage($r['test_score'],$r['test_total']);return ['from'=>$start,'through'=>$end,...$r];
}
function cssv_planner_reviews(PDO $pdo,string $user,string $attempt,string $today,array $c): array {
 $out=[];foreach([7,30] as $days){$start=cssv_planner_add_days($today,1-$days);$previousEnd=cssv_planner_add_days($start,-1);$out[(string)$days]=['current'=>cssv_planner_period($pdo,$user,$attempt,$start,$today,$c),'previous'=>cssv_planner_period($pdo,$user,$attempt,cssv_planner_add_days($start,-$days),$previousEnd,$c)];}
 return ['periods'=>$out,'basis'=>'Adjacent equal Karachi-date windows. Study/task minutes are self-reported, draft saves use server timestamps, linked practice retains the original event date, and human marks use the latest entered evaluation on its stated date. Imports are separate from newly studied units. Missing assessments stay null; no AI narrative or prediction.'];
}
