<?php
declare(strict_types=1);
require_once __DIR__.'/_planner.php';
function cssv_planner_import_preview(PDO $pdo,string $user,array $units): array {
 $q=$pdo->prepare('SELECT payload FROM student_progress WHERE user_id=?');$q->execute([$user]);$raw=$q->fetchColumn();$payload=$raw?json_decode($raw,true,64,JSON_THROW_ON_ERROR):[];$states=$payload['cssvista:v1']['syllabusItemStatuses']??[];$items=cssv_planner_import($units,is_array($states)?$states:[]);return ['items'=>$items,'hash'=>cssv_planner_hash($items),'basis'=>'Explicit copy of this account’s synced legacy syllabus states. Browser records stay intact. Earlier coverage is self-reported; no study date, test score or mastery is invented.'];
}
function cssv_planner_write_unit(PDO $pdo,string $user,string $attempt,array $u,array $r,string $coverage,?string $studied,?string $due,int $reviews,?array $extra=null): void {
 $source=$r['source']??['unit'=>$u];if(isset($source['unit'])&&cssv_planner_unit_hash($source['unit'])!==cssv_planner_unit_hash($u))throw new DomainException('This syllabus mapping changed. Your earlier progress is preserved; it needs a reviewed migration.');if($extra)$source=[...$source,...$extra];
 $pdo->prepare('INSERT INTO attempt_unit_progress(attempt_id,user_id,unit_id,version,coverage,last_studied,next_revision,review_count,source) VALUES(?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE version=VALUES(version),coverage=VALUES(coverage),last_studied=VALUES(last_studied),next_revision=VALUES(next_revision),review_count=VALUES(review_count)')->execute([$attempt,$user,$u['id'],($r['version']??0)+1,$coverage,$studied,$due,$reviews,json_encode($source,JSON_THROW_ON_ERROR)]);
}
function cssv_planner_new_task(PDO $pdo,string $user,string $plan,array $candidate): string {
 $id=cssv_uuid_v4();$pdo->prepare('INSERT INTO attempt_plan_tasks(id,plan_id,user_id,work_key,unit_id,kind,snapshot,minutes) VALUES(?,?,?,?,?,?,?,?)')->execute([$id,$plan,$user,$candidate['work_key'],$candidate['unit_id'],$candidate['kind'],json_encode($candidate,JSON_THROW_ON_ERROR),$candidate['minutes']]);return $id;
}
function cssv_planner_task_owned(PDO $pdo,string $user,string $attempt,string $id): array {$q=$pdo->prepare('SELECT t.*,p.plan_date,p.attempt_id FROM attempt_plan_tasks t JOIN attempt_daily_plans p ON p.id=t.plan_id WHERE t.id=? AND t.user_id=? AND p.user_id=? AND p.attempt_id=?');$q->execute([$id,$user,$user,$attempt]);$r=$q->fetch();if(!$r)throw new OutOfBoundsException('Plan task not found.');foreach(['version','minutes','actual_minutes'] as $k)$r[$k]=(int)$r[$k];$r['snapshot']=json_decode($r['snapshot'],true,32,JSON_THROW_ON_ERROR);return $r;}
function cssv_planner_mutation(PDO $pdo,string $user,array $body): array {
 $action=$body['action']??null;$base=['action','request_id','attempt_id'];
 cssv_pro_fields($body,match($action){'reading_save'=>[...$base,'expected_version','kind','source_id','source_hash','operation','outcome'],'settings_save'=>[...$base,'expected_version','religion_choice'],'coverage_save'=>[...$base,'expected_version','unit_id','coverage'],'coverage_import'=>[...$base,'import_hash'],'plan_save'=>[...$base,'date','expected_version','proposal_hash'],'task_work'=>[...$base,'task_id','expected_version','status','minutes','outcome'],'task_move'=>[...$base,'task_id','expected_version','date'],'evidence_link'=>[...$base,'unit_id','kind','source_id'],default=>throw new InvalidArgumentException('Choose a preparation action.')});
 $request=cssv_pro_id($body['request_id']??null);$attempt=cssv_pro_id($body['attempt_id']??null);$payload=$body;unset($payload['request_id']);$hash=cssv_planner_hash(['attempt-planner-v1',$payload]);$today=cssv_planner_day();
 $pdo->beginTransaction();try{
  cssv_learning_owner_lock($pdo,$user);$a=cssv_learning_attempt($pdo,$attempt,$user);$q=$pdo->prepare('SELECT payload_hash,result FROM learning_requests WHERE user_id=? AND request_id=?');$q->execute([$user,$request]);
  if($prior=$q->fetch()){if(!hash_equals($prior['payload_hash'],$hash))throw new DomainException('This save request was already used for different work.');$result=json_decode($prior['result'],true,32,JSON_THROW_ON_ERROR);if(($result['planner']??false)!==true)throw new DomainException('This receipt belongs to another learning action.');$pdo->commit();return $result;}
  $settings=cssv_planner_settings($pdo,$user,$attempt);$units=cssv_planner_selected($a,$settings['religion_choice']);$progress=cssv_planner_progress($pdo,$user,$attempt);$result=['planner'=>true,'attempt_id'=>$attempt];
  $expected=$body['expected_version']??null;if(in_array($action,['settings_save','coverage_save','plan_save','task_work','task_move'],true)&&(!is_int($expected)||$expected<0||$expected>1000000))throw new InvalidArgumentException('Reload the saved version before trying again.');
  if($action==='reading_save'){
   $result=[...$result,...cssv_reading_save($pdo,$user,$attempt,$body,$today)];
  }elseif($action==='settings_save'){
   if($settings['version']!==$expected)throw new DomainException('Planning settings changed elsewhere. Reload before saving.');$religion=$body['religion_choice']??null;if(!in_array($religion,['islamic-studies','comparative-religions'],true))throw new InvalidArgumentException('Choose the religion paper you intend to study.');
   $pdo->prepare('INSERT INTO attempt_planner_settings(attempt_id,user_id,version,religion_choice) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE version=VALUES(version),religion_choice=VALUES(religion_choice)')->execute([$attempt,$user,$expected+1,$religion]);cssv_planner_event($pdo,$user,$attempt,$action,['religion_choice'=>$religion,'previous'=>$settings['religion_choice']]);$result['version']=$expected+1;
  }elseif($action==='coverage_save'){
   $u=cssv_planner_unit($units,$body['unit_id']??null);$r=$progress[$u['id']]??[];if(($r['version']??0)!==$expected)throw new DomainException('This coverage record changed elsewhere. Reload before saving.');$coverage=$body['coverage']??null;if(!in_array($coverage,['not_started','learning','covered'],true))throw new InvalidArgumentException('Choose not started, learning or covered.');
   cssv_planner_write_unit($pdo,$user,$attempt,$u,$r,$coverage,$r['last_studied']??null,$coverage==='covered'?($r['next_revision']??$today):($r['next_revision']??null),$r['review_count']??0);cssv_planner_event($pdo,$user,$attempt,$action,['previous'=>$r['coverage']??'not_started','coverage'=>$coverage,'basis'=>'Self-reported coverage. Earlier study date unknown.'],null,$u['id']);$result['version']=$expected+1;
  }elseif($action==='coverage_import'){
   if(!$settings['religion_choice']||$settings['imported_at']||$progress)throw new DomainException('Earlier coverage can be copied only into an empty configured attempt. Existing records will not be overwritten.');$preview=cssv_planner_import_preview($pdo,$user,$units);if(!is_string($body['import_hash']??null)||!hash_equals($preview['hash'],$body['import_hash']))throw new DomainException('Synced earlier coverage changed. Review a fresh copy.');if(!$preview['items'])throw new DomainException('No matching synced earlier coverage is available.');
   foreach($preview['items'] as $item){$u=$units[$item['unit_id']];cssv_planner_write_unit($pdo,$user,$attempt,$u,[],$item['coverage'],null,$item['coverage']==='covered'?$today:null,0,['legacy_states'=>$item['legacy_states'],'imported'=>true]);}
   $pdo->prepare('UPDATE attempt_planner_settings SET imported_at=NOW(6),version=version+1 WHERE attempt_id=? AND user_id=?')->execute([$attempt,$user]);cssv_planner_event($pdo,$user,$attempt,$action,['items'=>$preview['items'],'source_hash'=>$preview['hash'],'basis'=>$preview['basis']]);$result['imported_units']=count($preview['items']);
  }elseif($action==='plan_save'){
   if(cssv_planner_date($body['date']??null)!==$today)throw new DomainException('The Pakistan planning day changed. Review today’s plan again.');$proposal=cssv_planner_proposal($pdo,$user,$attempt,$today);if($proposal['requires_setup'])throw new DomainException('Save the religion-paper study choice first.');
   if($proposal['expected_version']!==$expected||!is_string($body['proposal_hash']??null)||!hash_equals($proposal['hash'],$body['proposal_hash']))throw new DomainException('The plan, settings or evidence changed. Review the refreshed proposal before saving.');
   $plan=cssv_planner_plan($pdo,$user,$attempt,$today);$planId=$plan['id']??cssv_uuid_v4();if(!$plan)$pdo->prepare('INSERT INTO attempt_daily_plans(id,attempt_id,user_id,plan_date,budget,rule_version,input_hash,summary) VALUES(?,?,?,?,?,?,?,?)')->execute([$planId,$attempt,$user,$today,$proposal['budget'],$proposal['rule_version'],$proposal['hash'],json_encode($proposal['summary'],JSON_THROW_ON_ERROR)]);
   $tasks=array_column($plan['tasks']??[],null,'work_key');$selected=[];foreach($proposal['selection']['tasks'] as $candidate){if($candidate['unit_id']&&isset($units[$candidate['unit_id']]))$candidate['unit_source_hash']=cssv_planner_unit_hash($units[$candidate['unit_id']]);$existing=$tasks[$candidate['work_key']]??null;
    if($existing){if(!in_array($existing['status'],['pending','deferred'],true))throw new DomainException('A selected task changed. Refresh its plan.');$id=$existing['id'];$pdo->prepare("UPDATE attempt_plan_tasks SET status='pending',snapshot=?,minutes=?,version=version+1 WHERE id=? AND user_id=?")->execute([json_encode($candidate,JSON_THROW_ON_ERROR),$candidate['minutes'],$id,$user]);}
    else $id=cssv_planner_new_task($pdo,$user,$planId,$candidate);$selected[]=$candidate['work_key'];
    if(isset($candidate['carry_id'])){$old=cssv_planner_task_owned($pdo,$user,$attempt,$candidate['carry_id']);if($old['version']!==$candidate['carry_version']||!in_array($old['status'],['pending','partial'],true))throw new DomainException('Overdue work changed elsewhere. Review the recovery proposal.');$pdo->prepare("UPDATE attempt_plan_tasks SET status='moved',moved_to=?,version=version+1 WHERE id=?")->execute([$id,$old['id']]);$pdo->prepare('UPDATE attempt_daily_plans SET version=version+1 WHERE id=?')->execute([$old['plan_id']]);cssv_planner_event($pdo,$user,$attempt,'task_move',['from'=>$old['plan_date'],'to'=>$today,'moved_to'=>$id,'reason'=>'Reviewed missed-day recovery'],$old['id'],$old['unit_id']);}
   }
   foreach($plan['tasks']??[] as $old)if($old['status']==='pending'&&!in_array($old['work_key'],$selected,true))$pdo->prepare("UPDATE attempt_plan_tasks SET status='deferred',version=version+1 WHERE id=?")->execute([$old['id']]);
   $pdo->prepare('UPDATE attempt_daily_plans SET version=version+1,budget=?,rule_version=?,input_hash=?,summary=? WHERE id=? AND user_id=?')->execute([$proposal['budget'],$proposal['rule_version'],$proposal['hash'],json_encode($proposal['summary'],JSON_THROW_ON_ERROR),$planId,$user]);cssv_planner_event($pdo,$user,$attempt,$action,['reason'=>$plan?'Reviewed update to outstanding work. Completed/partial work retained.':'First reviewed daily plan.','proposal'=>$proposal]);$result['plan_id']=$planId;$result['version']=$expected+1;
  }elseif($action==='task_work'){
   $t=cssv_planner_task_owned($pdo,$user,$attempt,cssv_pro_id($body['task_id']??null));if($t['version']!==$expected||!in_array($t['status'],['pending','partial'],true))throw new DomainException('This task changed or was already finished. Reload before recording work.');if($t['plan_date']>$today)throw new DomainException('Record future work on its planning day, or move it to an earlier supported day.');
   $status=$body['status']??null;$minutes=$body['minutes']??null;if(!in_array($status,['partial','completed','skipped'],true)||!is_int($minutes)||$minutes<($status==='skipped'?0:1)||$minutes>$t['minutes']-$t['actual_minutes'])throw new InvalidArgumentException('Record valid actual minutes within the remaining allocation.');if($status==='partial'&&$minutes+$t['actual_minutes']>=$t['minutes'])throw new InvalidArgumentException('Use completed when all allocated minutes are recorded.');if($status==='skipped'&&$minutes!==0)throw new InvalidArgumentException('A skip records no new study minutes.');
   if($t['unit_id']&&isset(cssv_planner_catalog()[$t['unit_id']])){$u=cssv_planner_catalog()[$t['unit_id']];$r=$progress[$u['id']]??[];if(isset($t['snapshot']['unit_source_hash'])&&!hash_equals($t['snapshot']['unit_source_hash'],cssv_planner_unit_hash($u)))throw new DomainException('This saved task’s syllabus mapping changed. Its history is preserved for reviewed migration.');
    if($status==='completed'&&$t['kind']==='learn'){$newDue=cssv_planner_add_days($today,1);$due=isset($r['next_revision'])&&$r['next_revision']<$newDue?$r['next_revision']:$newDue;if(!in_array($body['outcome']??null,['studied','covered'],true))throw new InvalidArgumentException('Confirm whether the whole section is covered or still being studied.');$covered=($body['outcome']==='covered'||($r['coverage']??'')==='covered');cssv_planner_write_unit($pdo,$user,$attempt,$u,$r,$covered?'covered':'learning',$today,$covered?$due:($r['next_revision']??null),$r['review_count']??0);}
    elseif($status==='completed'&&$t['kind']==='revision'){if(($r['coverage']??'')!=='covered'||!isset($r['next_revision'])||$r['next_revision']>$today)throw new DomainException('This revision has already been resolved or its coverage changed. Reload and review the plan.');$review=cssv_planner_revision($today,$r['review_count'],$body['outcome']??'');cssv_planner_write_unit($pdo,$user,$attempt,$u,$r,'covered',$today,$review['next_revision'],$review['review_count']);}
    elseif($status==='partial'&&($r['coverage']??'not_started')==='not_started')cssv_planner_write_unit($pdo,$user,$attempt,$u,$r,'learning',null,null,0);
   }
   $pdo->prepare('UPDATE attempt_plan_tasks SET status=?,actual_minutes=actual_minutes+?,version=version+1 WHERE id=? AND user_id=?')->execute([$status,$minutes,$t['id'],$user]);$pdo->prepare('UPDATE attempt_daily_plans SET version=version+1 WHERE id=?')->execute([$t['plan_id']]);
   if($status==='completed'&&$t['kind']==='current_affairs'){$s=$t['snapshot'];$snap=['title'=>$s['title'],'edition_date'=>$s['edition_date'],'date'=>$today,'to'=>$s['to'],'basis'=>'Self-reported reading completion of a dated saved plan source; not a comprehension score.'];$pdo->prepare('INSERT IGNORE INTO attempt_evidence_links(attempt_id,user_id,evidence_key,kind,unit_id,source_id,snapshot) VALUES(?,?,?,?,NULL,?,?)')->execute([$attempt,$user,'current_affairs:'.$s['story_id'],'current_affairs',$s['story_id'],json_encode($snap,JSON_THROW_ON_ERROR)]);}
   cssv_planner_event($pdo,$user,$attempt,$action,['status'=>$status,'delta_minutes'=>$minutes,'kind'=>$t['kind'],'outcome'=>$body['outcome']??null,'previous_status'=>$t['status']],$t['id'],$t['unit_id']);$result['task_id']=$t['id'];$result['version']=$expected+1;
  }elseif($action==='task_move'){
   $old=cssv_planner_task_owned($pdo,$user,$attempt,cssv_pro_id($body['task_id']??null));if($old['version']!==$expected||!in_array($old['status'],['pending','partial'],true))throw new DomainException('This task changed or cannot be moved.');$date=cssv_planner_date($body['date']??null);if($date<=$today||$date>cssv_planner_add_days($today,365)||$date===$old['plan_date'])throw new InvalidArgumentException('Choose a different future day within one year.');$destination=cssv_planner_plan($pdo,$user,$attempt,$date);$budget=$destination?min($destination['budget'],$a['daily_minutes']):$a['daily_minutes'];$occupied=0;foreach($destination['tasks']??[] as $t){$occupied+=$t['actual_minutes'];if(in_array($t['status'],['pending','partial'],true))$occupied+=$t['minutes']-$t['actual_minutes'];if($t['work_key']===$old['work_key'])throw new DomainException('This work already has an identity on the destination day.');}
   $remaining=$old['minutes']-$old['actual_minutes'];if($occupied+$remaining>$budget)throw new DomainException('The remaining block will not fit the destination day’s budget. Choose another day or review its allocations.');$planId=$destination['id']??cssv_uuid_v4();if(!$destination)$pdo->prepare('INSERT INTO attempt_daily_plans(id,attempt_id,user_id,plan_date,budget,rule_version,input_hash,summary) VALUES(?,?,?,?,?,?,?,?)')->execute([$planId,$attempt,$user,$date,$budget,cssv_planner_rules()['version'],str_repeat('0',64),json_encode(['reason'=>'Explicitly rescheduled remaining work.'],JSON_THROW_ON_ERROR)]);
   $candidate=[...$old['snapshot'],'minutes'=>$remaining,'carried_from'=>$old['id']];unset($candidate['carry_id'],$candidate['carry_version']);$new=cssv_planner_new_task($pdo,$user,$planId,$candidate);$pdo->prepare("UPDATE attempt_plan_tasks SET status='moved',moved_to=?,version=version+1 WHERE id=? AND user_id=?")->execute([$new,$old['id'],$user]);$pdo->prepare('UPDATE attempt_daily_plans SET version=version+1 WHERE id IN (?,?)')->execute([$planId,$old['plan_id']]);cssv_planner_event($pdo,$user,$attempt,$action,['from'=>$old['plan_date'],'to'=>$date,'moved_to'=>$new,'preserved_minutes'=>$old['actual_minutes']],$old['id'],$old['unit_id']);$result['task_id']=$new;$result['date']=$date;
  }else{
   $kind=cssv_learning_string($body['kind']??null,32,'evidence type');$source=cssv_learning_string($body['source_id']??null,255,'source record');$unit=isset($body['unit_id'])?cssv_planner_unit($units,$body['unit_id']):null;if(in_array($kind,['mentor','mcq','past_paper'],true)&&!$unit)throw new InvalidArgumentException('Select the study unit this record belongs to.');
   $snapshot=cssv_planner_link_source($pdo,$user,$attempt,$kind,$source,$unit);$canonical=$kind==='mcq'?$snapshot['question_id']:(in_array($kind,['mpt','mentor'],true)?cssv_pro_id($source):$source);$key=$kind.':'.$canonical;
   $q=$pdo->prepare('SELECT unit_id FROM attempt_evidence_links WHERE attempt_id=? AND user_id=? AND evidence_key=?');$q->execute([$attempt,$user,$key]);$old=$q->fetch();if($old&&$old['unit_id']!==($unit['id']??null))throw new DomainException('This record is already linked to another study unit. It cannot be counted twice.');if(!$old){$pdo->prepare('INSERT INTO attempt_evidence_links(attempt_id,user_id,evidence_key,kind,unit_id,source_id,snapshot) VALUES(?,?,?,?,?,?,?)')->execute([$attempt,$user,$key,$kind,$unit['id']??null,$canonical,json_encode($snapshot,JSON_THROW_ON_ERROR)]);cssv_planner_event($pdo,$user,$attempt,$action,['kind'=>$kind,'source_id'=>$canonical,'snapshot'=>$snapshot],null,$unit['id']??null);}$result['evidence_key']=$key;
  }
  $pdo->prepare('INSERT INTO learning_requests(user_id,request_id,payload_hash,result) VALUES(?,?,?,?)')->execute([$user,$request,$hash,json_encode($result,JSON_THROW_ON_ERROR)]);$pdo->commit();return $result;
 }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
}
