<?php
declare(strict_types=1);
/** Fixed recognition drills adapted from the owner's handbook, not past questions. */
function cssv_precis_questions(): array {
 static $catalog;if($catalog!==null)return $catalog;$catalog=[];
 $add=function(string $id,string $skill,string $prompt,array $options,string $hint,string $explanation)use(&$catalog):void{
  $rotation=count($catalog)%count($options);$answer=$rotation;
  $options=array_merge(array_slice($options,count($options)-$rotation),array_slice($options,0,count($options)-$rotation));
  $catalog[$id]=compact('id','skill','prompt','options','answer','hint','explanation');
 };
 $add('central-science','central_idea','Research can improve health, agriculture and industry, but without ethical safeguards it may create risks. Which controlling idea covers both sides?', ['Scientific progress is most beneficial when innovation is guided by ethical responsibility.','Science is useful.','Scientific research should always be prohibited.'], 'Keep the benefit and the limit together.', 'The first idea needs the condition of responsibility. A broad topic omits it; prohibition contradicts the passage.');
 $add('central-press','central_idea','A free press can expose wrongdoing and inform citizens, yet careless reporting can spread falsehoods and damage trust. Choose the controlling idea.', ['Media freedom is strongest when accompanied by professional responsibility.','Newspapers report events.','A free press inevitably spreads falsehoods.'], 'Does your choice preserve the contrast?', 'Professional responsibility qualifies the value of press freedom. “Inevitably” strengthens a possibility into certainty.');
 $add('central-resources','central_idea','Natural resources can support prosperity, but poor governance may prevent benefits reaching ordinary lives. Effective and fair management matters more than possession alone.', ['Resource wealth benefits society through effective and fair management.','Natural resources guarantee prosperity.','Governance has no effect on prosperity.'], 'Possession alone is not the argument.', 'The controlling idea includes management, which the other choices contradict or omit.');
 $add('central-education','central_idea','Education can create opportunity, but unequal access may reproduce social divisions. A fair system must extend meaningful learning across society.', ['Educational opportunity requires broad, meaningful access.','Education creates qualifications.','Education always eliminates inequality.'], 'Protect the access condition.', 'The passage connects education with fairness of access; it does not claim automatic equality.');
 foreach([
 ['roads','roads, bridges, railways and ports','physical infrastructure','public healthcare','personal happiness'],
 ['schools','schools, universities and training centres','educational institutions','transport infrastructure','only universities'],
 ['needs','food, shelter, healthcare and education','basic needs and essential services','luxury goods','only public transport'],
 ['governance','corruption, weak accountability and selective enforcement','governance failures','all social activity','only financial debt'],
 ['finances','lost savings, debt and inability to afford necessities','financial insecurity','public services','political stability'],
 ['appeals','slogans, propaganda and personality worship','emotional or manipulative political appeals','all public debate','scientific research']
 ] as [$id,$list,$good,$bad,$narrow])$add('compress-'.$id,'compression','In this list, which umbrella expression covers the items without dropping their shared meaning: '.$list.'?',[$good,$bad,$narrow],'Choose a category that covers every item in this context.','The selected umbrella covers this list. Generalization must remain specific enough to preserve its relevant dimension.');
 $add('qualification-growth','qualifications','Growth can reduce poverty when employment expands broadly. Which version preserves the qualification?', ['Growth can reduce poverty through broadly expanding employment.','Growth always eliminates poverty.','Employment has no relation to poverty.'],'Protect “can” and the employment condition.','“Can” indicates possibility; broad employment is the condition.');
 $add('qualification-tech','qualifications','Technology may weaken judgment when dependence becomes excessive.', ['Excessive dependence on technology may weaken judgment.','Technology destroys judgment.','Technology invariably improves judgment.'],'Do not strengthen “may”.','The faithful version retains both possibility and excessive dependence.');
 $add('qualification-stability','qualifications','Political stability often encourages investment but does not guarantee development.', ['Stability often supports investment without ensuring development.','Stability guarantees development.','Stability prevents investment.'],'Both “often” and “does not guarantee” matter.','The qualification and contrast limit the original claim.');
 $add('qualification-freedom','qualifications','Freedom is valuable only when exercised with responsibility.', ['Freedom has value only when exercised responsibly.','Freedom is valuable in every circumstance.','Responsibility makes freedom valueless.'],'“Only when” is a necessary condition.','Removing the necessary condition changes the claim.');
 $add('select-condition','selection','Urbanization contributes to development only when services keep pace with growth. How should the condition be treated?', ['Keep its meaning.','Remove it as decorative language.','Replace it with your own recommendation.'],'Would removal change the argument?','Without the condition, a qualified claim becomes unconditional.');
 $add('select-list','selection','Housing, transport, sanitation, schools and hospitals illustrate several strained urban services. What is the best move?', ['Compress the list into accurate service categories.','Keep every noun regardless of the passage length.','Remove the strain on services entirely.'],'Keep the contribution to meaning while reducing detail.','The list can be compressed when its categories preserve the essential service pressure.');
 $add('select-example','selection','A particular exception is essential to the author’s main comparison. Should it disappear because it is an example?', ['Preserve the essential distinction concisely.','Remove every example automatically.','Replace it with a different case you know.'],'Judge its function, not its label.','An example that forms part of the claim is not merely illustration.');
 $add('select-repeat','selection','Two sentences repeat the same claim with different decoration. What should a précis normally do?', ['Express their shared claim once.','Retain both decorative versions.','Delete the central claim.'],'Merge repeated meaning.','Repetition can be removed without losing the claim itself.');
 $add('structure-cause','argument_structure','Weak institutions → corruption → declining trust → harder development. What structure is this?', ['Cause chain.','Unrelated list.','Sequence of official examination dates.'],'Follow the arrows between ideas.','Each move explains a consequence of the preceding weakness.');
 $add('structure-contrast','argument_structure','Technology improves efficiency; however, excessive dependence may weaken thought. What does “however” do?', ['Introduces a contrast.','Guarantees a result.','Adds a numerical example.'],'Notice the change in direction.','The second clause qualifies the benefit with a risk.');
 $add('structure-condition','argument_structure','A benefit occurs only when gains are broadly shared. What function does “only when” signal?', ['Necessary condition.','Illustration.','Repetition.'],'Ask what must hold for the claim to apply.','The benefit is conditional, not automatic.');
 $add('structure-remedy','argument_structure','After describing weak institutions and their effects, a passage concludes that institutional reform is needed. What is the final move?', ['Remedy / conclusion.','Decorative anecdote.','Unrelated quotation.'],'Link the final move to the problem.','Reform responds to the institutional problem and its effects.');
 $add('paraphrase-pressure','paraphrasing','In a passage about pressure on services, which concise substitution is faithful to “places pressure on”?', ['Strains.','Guarantees.','Eradicates.'],'Preserve the action, not just brevity.','“Strains” reduces the phrase without changing its relevant meaning.');
 $add('paraphrase-claim','paraphrasing','Choose a faithful concise version of “the failure of institutions undermines public confidence”.', ['Institutional failure undermines public confidence.','Institutional failure always destroys every society.','Public confidence causes all institutional failures.'],'Keep direction and strength.','The other versions exaggerate the claim or reverse its causal direction.');
 $add('fidelity-advice','fidelity','The passage contains no recommendation. Which addition would violate fidelity?', ['“We should therefore ban the technology.”','A concise restatement of the stated contrast.','A preserved qualification.'],'Do not add your own solution.','New advice absent from the original changes the author’s argument.');
 $add('fidelity-reversal','fidelity','The original says corruption reduces public trust. Which version distorts its causal direction?', ['Public trust causes corruption.','Corruption undermines public confidence.','Corruption lowers trust.'],'Which idea is cause, and which is effect?','Reversing cause and effect changes meaning even when the same nouns appear.');
 $add('coherence-link','coherence','Choose the coherent, grammatical sentence.', ['Despite economic growth, poverty remains.','Despite economic growth but poverty remains.','However, the rising inequality.'],'Use one correct contrast construction.','“Despite” takes a noun phrase here. The other options contain a faulty double link or fragment.');
 $add('coherence-pronoun','coherence','A précis uses “it” where either technology or dependence could be meant. What should you do?', ['Name the intended referent clearly.','Add more ambiguous pronouns.','Remove every logical link.'],'Can the reader identify the referent without the original?', 'Clear reference prevents ambiguity; shortness alone is not coherence.');
 $add('coherence-order','coherence','How should idea order usually work?', ['Preserve the argument’s progression unless a faithful minor reordering aids clarity.','Shuffle ideas to make the draft look different.','Always put an example before the claim.'],'Keep the miniature argument connected.','Arbitrary reordering can change emphasis and break the line of thought.');
 $add('grammar-modal','grammar','Choose the correct modal construction.', ['Unequal growth can intensify inequality.','Unequal growth can intensifies inequality.','Unequal growth can intensified inequality.'],'A modal takes the base form.','After “can”, use “intensify”. See Grammar Day 10 for modals.');
 $add('grammar-preposition','grammar','Choose the natural preposition.', ['The result depends on how it is used.','The result depends of how it is used.','The result depends at how it is used.'],'Recall the verb’s normal preposition.','Use “depends on”; revisit Grammar Day 16 for prepositions.');
 $add('grammar-agreement','grammar','Choose correct subject–verb agreement.', ['Economic opportunities are expanding.','Economic opportunities is expanding.','Economic opportunities was expanding.'],'The subject is plural.','“Opportunities” requires “are” here. Revisit Grammar Day 5.');
 $add('economy-because','economy','Replace “due to the fact that” without losing its causal function.', ['Because.','However.','Unless.'],'Keep cause as cause.','“Because” preserves the causal link with fewer words.');
 $add('economy-now','economy','Which is the concise equivalent of “at this point in time”?', ['Now.','Never.','Sometimes.'],'Preserve the time reference.','“Now” keeps the present reference.');
 $add('title-growth','title','A passage argues that growth matters when its benefits are widely shared. Which title best fits the controlling idea?', ['The Need for Inclusive Growth','Growth','The History of Factories'],'Title the argument, not a broad subject or minor detail.','Inclusive growth captures the distribution condition and covers the argument.');
 $add('title-digital','title','A passage values digital connection but calls for critical evaluation and responsible disagreement. Choose the best title.', ['Responsible Digital Literacy','Computers','The Speed of One Message'],'Keep both the benefit and the remedy in view.','The specific title covers responsible use and critical judgment.');
 $add('independence-reference','independence','Which feature prevents a précis from standing alone?', ['“This problem”, with no named problem anywhere in the précis.','A clearly stated central claim.','A complete sentence with an unambiguous referent.'],'Would a reader need the original to fill the gap?','An undefined reference depends on omitted context.');
 $add('independence-notes','independence','Choose the self-contained form.', ['Corruption weakens trust and development.','Trust. Corruption. Problems.','As mentioned in the third paragraph.'],'Use connected, complete wording.','The complete sentence can be understood without the original passage.');
 $add('grammar-article','grammar','Choose the natural form when “progress” means general advancement.', ['The reforms support real progress.','The reforms support a real progress.','The reforms support an real progress.'],'In this use, progress is uncountable.','Use “real progress” without an indefinite article. Revisit Grammar Day 13.');
 foreach(['grammar-modal'=>10,'grammar-preposition'=>16,'grammar-agreement'=>5,'grammar-article'=>13] as $id=>$day)$catalog[$id]['grammar_day']=$day;
 return $catalog;
}
