import { useEffect, useRef, useState } from 'react'
import { Columns2 } from 'lucide-react'
import { useLearning, type Writing } from '@/features/learning/api'
import { panelStyle, inputStyle, secondaryStyle } from '@/features/handwriting/styles'
import type { ComparisonData } from './api'
export default function Comparison({ writing, current, evidenceKey }: { writing: Writing; current: string; evidenceKey: string }) {
 const eligible = writing.versions.filter(v => v.version < (writing.versions.find(v => v.id === current)?.version || 0))
 const [before, setBefore] = useState(eligible[0]?.id || '')
 const { data, error, refresh } = useLearning<ComparisonData>(before ? `expression.php?before=${before}&after=${current}` : undefined)
 const evidence = useRef(evidenceKey)
 useEffect(() => { if (evidence.current === evidenceKey) return; evidence.current = evidenceKey; refresh() }, [evidenceKey, refresh])
 if (!eligible.length) return <p className="text-sm leading-7 text-slate-500">Save a later version to compare your revision with earlier wording.</p>
 return <section className={`${panelStyle} space-y-5`}><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="flex items-center gap-3 text-xl font-semibold tracking-tight"><Columns2 className="h-5 w-5 text-indigo-600" aria-hidden="true" />Compare your revisions</h2><button className={secondaryStyle} onClick={refresh}>Refresh comparison</button></div><label className="grid gap-2 text-sm font-semibold">Earlier version<select value={before} onChange={e => setBefore(e.target.value)} className={inputStyle}>{eligible.map(v => <option key={v.id} value={v.id}>Version {v.version}</option>)}</select></label>
  {!data ? <p role={error ? 'alert' : 'status'} className="text-sm leading-7">{error || 'Loading saved comparison…'}</p> : <><div className="grid gap-4 lg:grid-cols-2">{[data.comparison.before, data.comparison.after].map(v => <article key={v.id} className="min-w-0 rounded-2xl border border-slate-200 bg-slate-50/60 p-5"><h3 className="text-sm font-semibold">Version {v.version} · {v.word_count} words</h3><p className="mt-4 whitespace-pre-wrap break-words text-sm leading-8">{v.text}</p></article>)}</div><p className="text-sm leading-7 text-slate-500">{data.comparison.same_wording ? 'The saved wording is identical.' : `Word count changed by ${data.comparison.word_delta > 0 ? '+' : ''}${data.comparison.word_delta}. A shorter version is not automatically better.`} Comparison uses saved wording and feedback; it makes no AI call.</p>{!data.comparison.feedback_available ? <p className="rounded-xl bg-indigo-50 p-4 text-sm leading-7 text-indigo-950">Feedback is needed on both versions to compare reported findings. You can still compare the wording above.</p> : <><div className="grid gap-4 sm:grid-cols-3">{[{ title: 'No longer reported', codes: data.comparison.no_longer_reported }, { title: 'Still reported', codes: data.comparison.still_reported }, { title: 'Newly reported', codes: data.comparison.newly_reported }].map(group => <article key={group.title} className="rounded-xl border border-slate-200 p-4"><h3 className="text-sm font-semibold">{group.title}</h3><ul className="mt-3 space-y-2 text-sm leading-6 text-slate-600">{group.codes.length ? group.codes.map(code => <li key={code}>{data.skills[code]?.label || code}</li>) : <li>None in these findings</li>}</ul></article>)}</div><p className="text-xs leading-6 text-slate-500">These are differences between saved model findings. An omitted category does not prove that every issue is resolved. Check the revised wording yourself.</p></>}</>}
 </section>
}
