<?php
declare(strict_types=1);
if(getenv('CI')!=='true'||getenv('CSSV_DB_NAME')!=='cssvista_briefing_test')throw new RuntimeException('Disposable test database only.');
require __DIR__.'/../../public/api/_bootstrap.php';require __DIR__.'/../../public/api/_planner_mutations.php';$pdo=cssv_db();cssv_planner_ensure($pdo);$user=cssv_pro_id($argv[2]??null);$attempt=cssv_pro_id($argv[3]??null);cssv_learning_attempt($pdo,$attempt,$user);
if($argv[1]==='clear-rate'){$pdo->exec("DELETE FROM login_security_events WHERE event_type='planner_write'");}
elseif($argv[1]==='legacy'){$units=cssv_planner_selected(cssv_learning_attempt($pdo,$attempt,$user),'islamic-studies');$u=reset($units);$payload=['cssvista:v1'=>['syllabusItemStatuses'=>array_fill_keys($u['legacy_ids'],'completed')]];$pdo->prepare('INSERT INTO student_progress(user_id,payload,client_updated_at) VALUES(?,?,NOW(6)) ON DUPLICATE KEY UPDATE payload=VALUES(payload)')->execute([$user,json_encode($payload)]);echo $u['id'];}
elseif($argv[1]==='practice'){$q=$pdo->prepare('INSERT INTO question_attempts(user_id,question_id,category,topic,correct,attempted_at,event_key) VALUES(?,?,?,?,?,?,?)');$q->execute([$user,'TEST-'.$attempt,'TEST ONLY','TEST ONLY linked practice',0,'2001-02-03 00:00:00',cssv_uuid_v4()]);$q->execute([$user,'TEST-'.$attempt,'TEST ONLY','TEST ONLY retry',1,'2001-02-04 00:00:00',cssv_uuid_v4()]);$ids=[];foreach([[1,2],[9,100]] as [$score,$total]){$pdo->prepare('INSERT INTO quiz_attempts(user_id,attempt_key,quiz_type,category,score,total,completed_at,metadata) VALUES(?,?,?,?,?,?,?,?)')->execute([$user,cssv_uuid_v4(),'practice','TEST ONLY',$score,$total,'2001-02-03 00:00:00','{}']);$ids[]=$pdo->lastInsertId();}$pdo->prepare('INSERT INTO quiz_attempts(user_id,attempt_key,quiz_type,category,score,total,completed_at,metadata) VALUES(?,?,?,?,?,?,?,?)')->execute([$user,cssv_uuid_v4(),'TEST ONLY','TEST ONLY legacy MPT',100,100,'2001-02-03 00:00:00',json_encode(['mock_kind'=>'mpt'])]);echo json_encode(['question'=>'TEST-'.$attempt,'tests'=>$ids,'legacy'=>$pdo->lastInsertId()]);}
elseif($argv[1]==='yesterday'){$q=$pdo->prepare('UPDATE attempt_daily_plans SET plan_date=? WHERE user_id=? AND attempt_id=?');$q->execute([cssv_planner_add_days(cssv_planner_day(),-1),$user,$attempt]);}
elseif($argv[1]==='changed'){$q=$pdo->prepare('SELECT source FROM attempt_unit_progress WHERE attempt_id=? AND user_id=? LIMIT 1');$q->execute([$attempt,$user]);$source=json_decode($q->fetchColumn(),true);$source['unit']['title'].=' TEST CHANGED';$pdo->prepare('UPDATE attempt_unit_progress SET source=? WHERE attempt_id=? AND user_id=?')->execute([json_encode($source),$attempt,$user]);}
elseif($argv[1]==='counts'){$out=[];foreach(['attempt_daily_plans','attempt_plan_tasks','attempt_planner_events','attempt_evidence_links','ai_operations'] as $table){$q=$pdo->prepare('SELECT COUNT(*) FROM '.$table.' WHERE user_id=?');$q->execute([$user]);$out[$table]=(int)$q->fetchColumn();}echo json_encode($out);}
elseif($argv[1]==='mpt'){
 require __DIR__.'/../../public/api/_mpt_schema.php';foreach(cssv_mpt_schema_statements() as $sql)$pdo->exec($sql);
 $mock=cssv_uuid_v4();$session=cssv_uuid_v4();$application=cssv_uuid_v4();$code='T'.substr(str_replace('-','',$mock),0,18);$now=gmdate('Y-m-d H:i:s');$future=gmdate('Y-m-d H:i:s',time()+86400);
 $pdo->prepare("INSERT INTO mpt_mocks(id,public_slug,mock_number,title,status,application_open_at,application_close_at,exam_open_at,entry_close_at,exam_end_at,duration_minutes,total_marks,results_release_policy) VALUES(?,?,?,'TEST ONLY planner source','PUBLISHED',?,?,?,?,?,120,100,'AFTER_WINDOW')")->execute([$mock,$code,random_int(500000000,2000000000),$now,$future,$now,$future,$future]);
 $pdo->prepare('INSERT INTO mpt_sessions(id,mock_id,starts_at,ends_at) VALUES(?,?,?,?)')->execute([$session,$mock,$now,$future]);$pdo->prepare('INSERT INTO mpt_applications(id,application_code,user_id,mock_id,session_id,roll_number,applied_at) VALUES(?,?,?,?,?,?,?)')->execute([$application,$code,$user,$mock,$session,'000000000001',$now]);$ids=[];
 foreach([1,2] as $number){$id=cssv_uuid_v4();$pdo->prepare("INSERT INTO mpt_attempts(id,application_id,attempt_no,user_id,mock_id,status,started_at,expires_at,submitted_at,active_session_id,score,total_marks) VALUES(?,?,?,?,?,'SUBMITTED',?,?,?,'TEST ONLY',?,100)")->execute([$id,$application,$number,$user,$mock,$now,$future,$now,$number===1?30:80]);$ids[]=$id;}echo json_encode(['ids'=>$ids,'mock'=>$mock]);
}elseif(in_array($argv[1],['release','void'],true)){$id=cssv_pro_id($argv[4]??null);if($argv[1]==='release')$pdo->prepare("UPDATE mpt_mocks SET results_release_policy='IMMEDIATE_SCORE' WHERE id=? AND title='TEST ONLY planner source'")->execute([$id]);else $pdo->prepare('UPDATE mpt_attempts SET voided_at=NOW() WHERE id=? AND user_id=?')->execute([$id,$user]);}
else throw new RuntimeException('Unknown fixture.');
