import assert from 'node:assert/strict'
import { randomUUID } from 'node:crypto'
import { execFileSync } from 'node:child_process'
if(process.env.CI!=='true'||process.env.CSSV_DB_NAME!=='cssvista_briefing_test')throw new Error('Disposable database required')
const env={...process.env};for(const k of ['DOCKER_HOST','DOCKER_CONTEXT','DOCKER_TLS','DOCKER_TLS_VERIFY','DOCKER_CERT_PATH'])delete env[k]
const php=(...args)=>process.env.CSSV_TEST_PHP_CONTAINER?execFileSync('docker',['--host=unix:///var/run/docker.sock','exec',process.env.CSSV_TEST_PHP_CONTAINER,'php',...args],{env,encoding:'utf8'}).trim():execFileSync('php',args,{env,encoding:'utf8'}).trim()
async function call(path,body,jar=new Map(),extra={}){const headers={Accept:'application/json','User-Agent':'CSSVistaPlannerIsolation',...extra};if(jar.size)headers.Cookie=[...jar].map(([k,v])=>`${k}=${v}`).join('; ');if(body){headers['Content-Type']='application/json';headers['X-CSRF-Token']??=jar.get('cssv_csrf')||''}const r=await fetch('http://localhost:4173/api/'+path,{headers,...(body?{method:'POST',body:JSON.stringify(body)}:{})});for(const c of r.headers.getSetCookie()){const p=c.split(';')[0],i=p.indexOf('=');jar.set(p.slice(0,i),p.slice(i+1))}const raw=await r.text();let data;try{data=JSON.parse(raw)}catch{throw new Error(`Non-JSON ${r.status} from ${path}: ${raw.slice(0,2400)}`)}return{status:r.status,data,headers:r.headers}}
async function user(label){const email=`planner-${label}-${randomUUID()}@example.invalid`,id=php('tests/current-affairs/setup.php','user',email),jar=new Map();assert.equal((await call('auth/login.php',{email,password:'TEST ONLY native fixture password'},jar)).status,200);return{id,jar}}
const a=await user('a'),b=await user('b'),bad=await user('incomplete'),imported=await user('import'),recover=await user('missed')
const settings={action:'attempt_save',expected_version:0,target_year:2027,target_date:null,daily_minutes:90,stage:'starting',optional_subject_ids:[]}
async function make(u){const r=await call('student/learning.php',{...settings,request_id:randomUUID()},u.jar);assert.equal(r.status,200,JSON.stringify(r.data));return r.data.attempt_id}
const attempt=await make(a),bAttempt=await make(b),iAttempt=await make(imported),rAttempt=await make(recover)
php('tests/planner/fixture.php','clear-rate',a.id,attempt)
const endpoint='student/planner.php'
const get=(view='plan',u=a,id=attempt,query='')=>call(`${endpoint}?attempt=${id}&view=${view}${query}`,undefined,u.jar)
const mutate=(body,u=a,id=attempt)=>call(endpoint,{request_id:randomUUID(),attempt_id:id,...body},u.jar)
async function ok(body,u=a,id=attempt){const r=await mutate(body,u,id);assert.equal(r.status,200,JSON.stringify(r.data));return r.data.result}
assert.equal((await call(endpoint)).status,401);assert.equal((await call(endpoint+`?attempt=${attempt}`,undefined,a.jar,{'X-CSSV-User':b.id})).status,409)
php('tests/pro/fixture.php','incomplete',bad.id);assert.equal((await call(endpoint,undefined,bad.jar)).status,403)
assert.equal((await get('plan',b,attempt)).status,404)
assert.equal((await call(endpoint,{action:'settings_save',attempt_id:attempt,request_id:randomUUID(),expected_version:0,religion_choice:'islamic-studies'},a.jar,{'X-CSRF-Token':'wrong'})).status,403)
assert.equal((await mutate({action:'settings_save',expected_version:0,religion_choice:'islamic-studies',user_id:b.id})).status,422)
let data=(await get()).data;assert.equal(data.proposal.requires_setup,true);assert.equal(data.plan,null);assert.match((await get()).headers.get('cache-control'),/no-store/)
const configured={action:'settings_save',request_id:randomUUID(),expected_version:0,religion_choice:'islamic-studies'};await ok(configured);await ok(configured);assert.equal((await mutate({...configured,religion_choice:'comparative-religions'})).status,409)
for(const [u,id] of [[imported,iAttempt],[recover,rAttempt],[b,bAttempt]])await ok({action:'settings_save',expected_version:0,religion_choice:'islamic-studies'},u,id)
let preview=(await get()).data.proposal
const coverage=(await get('coverage')).data;const unit=coverage.units[0]
await ok({action:'coverage_save',unit_id:unit.id,expected_version:0,coverage:'covered'})
assert.equal((await mutate({action:'plan_save',date:preview.date,proposal_hash:preview.hash,expected_version:0})).status,409,'Stale evidence proposal accepted')
data=(await get()).data;assert.equal(data.revision_total,1);assert.equal(data.proposal.selection.tasks[0].kind,'revision');assert.ok(data.proposal.selection.allocated_minutes<=90)
async function savePlan(u=a,id=attempt){const p=(await get('plan',u,id)).data.proposal;return ok({action:'plan_save',date:p.date,proposal_hash:p.hash,expected_version:p.expected_version},u,id)}
await savePlan();let plan=(await get()).data.plan;const revision=plan.tasks.find(t=>t.kind==='revision')
const work={action:'task_work',request_id:randomUUID(),task_id:revision.id,expected_version:1,status:'completed',minutes:revision.minutes,outcome:'needs_review'};await ok(work);await ok(work)
assert.equal((await get('coverage')).data.units.find(u=>u.id===unit.id).next_revision,php('tests/planner/date.php','next'))
assert.equal((await mutate({...work,request_id:randomUUID()})).status,409,'Finished task repeated')
const other=plan.tasks.find(t=>t.kind!=='revision');await ok({action:'task_work',task_id:other.id,expected_version:1,status:'partial',minutes:2});const partial=(await get()).data.plan.tasks.find(t=>t.id===other.id);assert.equal(partial.actual_minutes,2)
await savePlan();plan=(await get()).data.plan;assert.equal(plan.tasks.find(t=>t.id===partial.id).status,'partial');assert.equal(plan.tasks.find(t=>t.id===revision.id).status,'completed')
const date=php('tests/planner/date.php','next');const moved=await ok({action:'task_move',task_id:partial.id,expected_version:partial.version,date});const future=(await get('day',a,attempt,'&date='+date)).data.plan;assert.equal(future.tasks[0].id,moved.task_id);assert.equal(future.tasks[0].minutes,partial.minutes-2)
assert.equal((await mutate({action:'task_work',task_id:moved.task_id,expected_version:1,status:'completed',minutes:future.tasks[0].minutes})).status,409,'Future work received premature credit')
assert.equal((await get('day',b,attempt,'&date='+date)).status,404)
const receipt=(await call(endpoint+'?request_id='+work.request_id,undefined,a.jar));assert.equal(receipt.data.result.task_id,revision.id);assert.equal((await call(endpoint+'?request_id='+work.request_id,undefined,b.jar)).status,404)
const practice=JSON.parse(php('tests/planner/fixture.php','practice',a.id,attempt));await ok({action:'evidence_link',kind:'mcq',source_id:practice.question,unit_id:unit.id});await ok({action:'evidence_link',kind:'mcq',source_id:practice.question,unit_id:unit.id});assert.equal((await mutate({action:'evidence_link',kind:'mcq',source_id:practice.question,unit_id:coverage.units[1].id})).status,409)
for(const id of practice.tests)await ok({action:'evidence_link',kind:'test',source_id:id,unit_id:unit.id})
assert.equal((await mutate({action:'evidence_link',kind:'test',source_id:practice.tests[0]+'abc',unit_id:unit.id})).status,422)
const tests=(await get('sources',a,attempt,'&kind=test'));assert.equal(tests.status,200);assert.ok(!tests.data.records.some(r=>String(r.source_id)===practice.legacy),'Legacy browser MPT listed as a verified test');assert.equal((await mutate({action:'evidence_link',kind:'test',source_id:practice.legacy})).status,422);assert.equal((await mutate({action:'evidence_link',kind:'mcq',source_id:practice.question,unit_id:unit.id},b,bAttempt)).status,404,'Foreign practice linked');assert.equal((await get('events')).status,200);assert.equal((await get('events',b,attempt)).status,404)
let readiness=(await get('readiness')).data.dimensions;assert.equal(readiness.mcq.total,1);assert.equal(readiness.mcq.correct,0,'Retry inflated first responses');assert.equal(readiness.tests.percentage,9.8);assert.equal(readiness.mentor.first.percentage,null);assert.equal(readiness.overall_percentage,null)
let report=(await get('reviews')).data.reviews.periods['7'].current;assert.equal(report.mcq_questions,0,'Attaching old evidence invented recent practice');assert.equal(report.test_total,0);assert.equal(report.minutes,revision.minutes+2)
php('tests/planner/fixture.php','legacy',imported.id,iAttempt);const imp=(await get('import',imported,iAttempt)).data;await ok({action:'coverage_import',import_hash:imp.hash},imported,iAttempt);const iu=(await get('coverage',imported,iAttempt)).data.units.find(u=>u.coverage==='covered');assert.equal(iu.last_studied,null);assert.equal(iu.next_revision,(await get('plan',imported,iAttempt)).data.today);assert.ok(iu.imported_states)
assert.equal((await mutate({action:'coverage_import',import_hash:imp.hash},imported,iAttempt)).status,409,'Import overwrote existing work')
php('tests/planner/fixture.php','changed',imported.id,iAttempt);assert.equal((await get('coverage',imported,iAttempt)).data.coverage.covered,0);assert.equal((await mutate({action:'coverage_save',unit_id:iu.id,expected_version:iu.version,coverage:'covered'},imported,iAttempt)).status,409,'Changed mapping silently credited')
await savePlan(recover,rAttempt);php('tests/planner/fixture.php','yesterday',recover.id,rAttempt);data=(await get('plan',recover,rAttempt)).data;assert.ok(data.overdue.length);assert.ok(data.proposal.selection.allocated_minutes<=90);await savePlan(recover,rAttempt);assert.ok((await get('history',recover,rAttempt)).data.plans.length===2)
const raceBody={action:'coverage_save',unit_id:coverage.units[1].id,expected_version:0,coverage:'covered'};const raced=await Promise.all([mutate(raceBody),mutate({...raceBody,coverage:'learning'})]);assert.deepEqual(raced.map(r=>r.status).sort(),[200,409],'Coverage race lost a version')
const mpt=JSON.parse(php('tests/planner/fixture.php','mpt',a.id,attempt));assert.equal((await mutate({action:'evidence_link',kind:'mpt',source_id:mpt.ids[0]})).status,404,'Unreleased marks leaked');php('tests/planner/fixture.php','release',a.id,attempt,mpt.mock);assert.equal((await mutate({action:'evidence_link',kind:'mpt',source_id:mpt.ids[0]},b,bAttempt)).status,404,'Foreign MPT linked');for(const id of mpt.ids)await ok({action:'evidence_link',kind:'mpt',source_id:id});readiness=(await get('readiness')).data.dimensions;assert.equal(readiness.mpt.first.percentage,30);assert.equal(readiness.mpt.repeats.percentage,80);php('tests/planner/fixture.php','void',a.id,attempt,mpt.ids[0]);assert.equal((await get('readiness')).data.dimensions.mpt.first.percentage,null,'Voided result still counted');
php('tests/precis/fixture.php','activate',a.id)
const mentorCall=async body=>{const r=await call('student/mentor.php',{request_id:randomUUID(),...body},a.jar);assert.equal(r.status,200,JSON.stringify(r.data));return r.data};
for(const [obtained,maximum] of [[1,2],[9,100]]){const answer=(await mentorCall({action:'question_save',expected_version:0,attempt_id:attempt,subject_id:unit.subject_id,topic:'TEST ONLY weighted topic',question:'TEST ONLY independent practice?',provenance:'practice',source_reference:''})).answer_id;await mentorCall({action:'written_save',id:answer,expected_version:1,written_date:(await get()).data.today});await mentorCall({action:'evaluation_save',id:answer,expected_version:2,obtained_marks:obtained,maximum_marks:maximum,evaluation_date:(await get()).data.today,mentor_comment:'TEST ONLY human feedback',correction_reason:''});await ok({action:'evidence_link',kind:'mentor',source_id:answer,unit_id:unit.id})}
assert.equal((await get('readiness')).data.dimensions.mentor.first.percentage,9.8,'Human unequal marks averaged incorrectly');
php('tests/precis/fixture.php','activate',a.id);assert.equal((await get()).data.active,true);php('tests/pro/fixture.php','expire',a.id);assert.equal((await get()).data.active,false);assert.equal((await get('readiness')).status,200,'Expiry erased free preparation evidence');assert.equal((await call(endpoint+'?request_id='+work.request_id,undefined,a.jar)).status,200)
assert.equal(JSON.parse(php('tests/planner/fixture.php','counts',a.id,attempt)).ai_operations,0,'Planner dispatched AI')
for(const f of ['_planner.php','_planner_core.php','_planner_rules.php','_planner_reports.php','_planner_sources.php','_planner_mutations.php','_planner_schema.php'])assert.equal((await fetch('http://localhost:4173/api/'+f)).status,404)
console.log('PASS: native planner free/expiry ownership, full profile, CSRF/account binding, review/hash/version races, exact receipt recovery, partial/completed/moved histories, future guards, revision, explicit non-destructive legacy import, source revisions, owned first-response evidence, weighted human/test marks, released/voided native MPT with separate retries, legacy MPT exclusion, original date reviews and zero AI dispatch.')
