<?php
declare(strict_types=1);
require __DIR__.'/../../public/api/_planner_core.php';require __DIR__.'/../../public/api/_planner_schema.php';require __DIR__.'/../../public/api/_planner_reports.php';
$n=0;function check(bool $v,string $why):void{global $n;$n++;if(!$v)throw new RuntimeException($why);}
check(cssv_planner_day(new DateTimeImmutable('2026-10-07T18:59:59Z'))==='2026-10-07','Before Karachi midnight');check(cssv_planner_day(new DateTimeImmutable('2026-10-07T19:00:00Z'))==='2026-10-08','Karachi midnight');
foreach(['2026-02-30','1999-12-31','2101-01-01','2026-1-01'] as $day){try{cssv_planner_date($day);throw new RuntimeException('Invalid day accepted');}catch(InvalidArgumentException){$n++;}}
$a=['optional_subject_ids'=>['political-science'],'target_date'=>'2027-02-20','daily_minutes'=>60];$units=cssv_planner_selected($a,'islamic-studies');check(count($units)>40,'Real source sections');check(isset($units['essay:practice']),'Essay separately retained');check(!count(array_filter($units,fn($u)=>$u['subject_id']==='comparative-religions')),'Religion alternatives exclusive');check(!count(array_filter($units,fn($u)=>$u['designation']==='optional'&&$u['subject_id']!=='political-science')),'Only shortlisted optionals');
$u=reset($units);$states=array_fill_keys($u['legacy_ids'],'completed');$import=cssv_planner_import([$u['id']=>$u],$states);check($import[0]['coverage']==='covered','All source lines covered');unset($states[array_key_first($states)]);check(cssv_planner_import([$u['id']=>$u],$states)[0]['coverage']==='learning','Missing line prevents full credit');
$r=['coverage'=>'covered','source'=>['unit'=>$u]];$capacity=cssv_planner_capacity($a,$units,[$u['id']=>$r],'2026-10-08');check($capacity['covered']===1,'Self report count');$old=$u;$old['title'].=' changed';$r['source']['unit']=$old;check(cssv_planner_source_changed($u,$r),'Mapping semantic revision detected');check(cssv_planner_capacity($a,$units,[$u['id']=>$r],'2026-10-08')['covered']===0,'Revised mapping excluded from coverage');check($capacity['total']===count($units)-1,'Essay excluded from syllabus denominator');
$review=cssv_planner_revision('2026-10-08',0,'recalled');check($review['next_revision']==='2026-10-11','Successful first revision +3');check(cssv_planner_revision('2026-10-08',4,'recalled')['next_revision']==='2026-11-07','Maintenance +30');check(cssv_planner_revision('2026-10-08',4,'needs_review')['next_revision']==='2026-10-09','Difficulty +1');
$cs=[['work_key'=>'a','lane'=>'revision','priority'=>100,'minutes'=>20],['work_key'=>'b','lane'=>'grammar','priority'=>95,'minutes'=>20],['work_key'=>'c','lane'=>'coverage','priority'=>40,'minutes'=>30],['work_key'=>'d','lane'=>'coverage','priority'=>40,'minutes'=>30]];
check(array_column(cssv_planner_allocate($cs,60,[])['tasks'],'minutes')===[20,20,20],'60 minute due/grammar/coverage mix');check(cssv_planner_allocate($cs,15,[])['tasks'][0]['minutes']===15,'15 minute budget');check(cssv_planner_allocate($cs,14,[])['tasks']===[],'No unusable small block');check(cssv_planner_allocate(array_reverse($cs),60,[])===cssv_planner_allocate($cs,60,[]),'Stable tie breaks');
$routine=[['work_key'=>'g','lane'=>'grammar','priority'=>55,'minutes'=>20],['work_key'=>'s','lane'=>'coverage','priority'=>40,'minutes'=>30],['work_key'=>'w','lane'=>'writing','priority'=>45,'minutes'=>30]];$lanes=[];for($i=0;$i<3;$i++)$lanes[]=cssv_planner_allocate($routine,15,[],cssv_planner_add_days('2026-10-08',$i))['tasks'][0]['lane'];check(count(array_unique($lanes))===3,'Small budgets rotate routine lanes without starving syllabus');
$urgent=[...$cs,['work_key'=>'z','lane'=>'revision','priority'=>99,'minutes'=>20]];check(array_column(cssv_planner_allocate($urgent,60,[],'2026-10-08')['tasks'],'work_key')===['a','z','b'],'All urgent revision precedes routine work');
$t=[['work_key'=>'a','status'=>'completed','minutes'=>20,'actual_minutes'=>20],['work_key'=>'b','status'=>'partial','minutes'=>20,'actual_minutes'=>5]];$alloc=cssv_planner_allocate($cs,60,$t);check(count($alloc['locked'])===1,'Partial stays locked');check(array_column($alloc['tasks'],'work_key')===['c'],'Completed never returned');check($alloc['allocated_minutes']===60,'Actual plus locked remainder budget');check(cssv_planner_allocate($cs,15,$t)['recorded_over_budget_minutes']===25,'Budget decrease does not erase earlier work');
for($budget=15;$budget<=1440;$budget+=15){$x=cssv_planner_allocate($cs,$budget,[]);check(array_sum(array_column($x['tasks'],'minutes'))<=$budget,'Budget cap');check($x['allocated_minutes']+$x['remaining_minutes']===$budget,'Accounting');}
check(cssv_planner_percentage(0,0)===null,'Missing evidence null');check(cssv_planner_percentage(1+9,2+100)===9.8,'Unequal test weighted sum');check(cssv_planner_hash(['b'=>2,'a'=>1])===cssv_planner_hash(['a'=>1,'b'=>2]),'MySQL key order stable');
$sql=file_get_contents(__DIR__.'/../../server/sql/020_attempt_planner.sql');preg_match_all('/CREATE TABLE IF NOT EXISTS [\s\S]*?;/',$sql,$m);check(array_map(fn($v)=>trim($v,"; \n\r"),$m[0])===cssv_planner_schema_statements(),'Additive SQL/runtime parity');
echo "PASS: $n assertions — deterministic budgets, source sections, explicit legacy coverage, mapping revisions, no invented full credit, revision intervals, equal dates, weighted scores and schema parity.\n";
