<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/_bootstrap.php';require_once dirname(__DIR__).'/_planner_mutations.php';require_once dirname(__DIR__).'/_planner_reports.php';
cssv_require_method('GET','POST');
try{
 $pdo=cssv_db();$session=cssv_require_user($pdo);$user=(string)$session['user_id'];if($_SERVER['REQUEST_METHOD']==='POST')cssv_require_csrf($session);cssv_planner_ensure($pdo);
 if($_SERVER['REQUEST_METHOD']==='POST'){cssv_enforce_rate_limit($pdo,'planner_write',$user,240,3600);cssv_log_security_event($pdo,'planner_write',$user,$user);$body=cssv_request_json(12000);if(($body['action']??null)==='reading_save')ca_sync_git_release($pdo);cssv_json(['ok'=>true,'result'=>cssv_planner_mutation($pdo,$user,$body)]);}
 cssv_pro_fields($_GET,['overview','attempt','request_id','view','subject','unit','kind','offset','date','source_id','filter','range']);
 if(isset($_GET['request_id'])){$q=$pdo->prepare('SELECT result FROM learning_requests WHERE user_id=? AND request_id=?');$q->execute([$user,cssv_pro_id($_GET['request_id'])]);$raw=$q->fetchColumn();$r=$raw?json_decode($raw,true,32,JSON_THROW_ON_ERROR):null;if(!$r||($r['planner']??false)!==true)throw new OutOfBoundsException('No accepted preparation action was found.');cssv_learning_attempt($pdo,$r['attempt_id'],$user);cssv_json(['ok'=>true,'result'=>$r]);}
 if(isset($_GET['overview'])){$q=$pdo->prepare('SELECT id,target_year,daily_minutes,target_date FROM preparation_attempts WHERE user_id=? ORDER BY updated_at DESC,id LIMIT 50');$q->execute([$user]);cssv_json(['ok'=>true,'attempts'=>$q->fetchAll()]);}
 $attempt=cssv_pro_id($_GET['attempt']??null);$a=cssv_learning_attempt($pdo,$attempt,$user);$today=cssv_planner_day();$settings=cssv_planner_settings($pdo,$user,$attempt);$units=cssv_planner_selected($a,$settings['religion_choice']);$view=$_GET['view']??'plan';
 $offset=filter_var($_GET['offset']??0,FILTER_VALIDATE_INT,['options'=>['min_range'=>0,'max_range'=>100000]]);if($offset===false)throw new InvalidArgumentException('Choose a valid page.');
 if($view==='reading'){ca_sync_git_release($pdo);cssv_json(['ok'=>true,...cssv_reading_view($pdo,$user,$attempt,$_GET)]);}
 if($view==='import')cssv_json(['ok'=>true,...cssv_planner_import_preview($pdo,$user,$units)]);
 if($view==='sources'){$unit=isset($_GET['unit'])?cssv_planner_unit($units,$_GET['unit']):null;cssv_json(['ok'=>true,...cssv_planner_sources($pdo,$user,$attempt,cssv_learning_string($_GET['kind']??null,32,'evidence type'),$unit,$offset)]);}
 if($view==='history'){$q=$pdo->prepare('SELECT id,plan_date,version,budget,rule_version,summary FROM attempt_daily_plans WHERE user_id=? AND attempt_id=? ORDER BY plan_date DESC LIMIT 31 OFFSET '.$offset);$q->execute([$user,$attempt]);$rows=$q->fetchAll();$more=count($rows)>30;foreach($rows as &$r)$r['summary']=json_decode($r['summary'],true,32,JSON_THROW_ON_ERROR);unset($r);cssv_json(['ok'=>true,'plans'=>array_slice($rows,0,30),'has_more'=>$more]);}
 if($view==='day'){$date=cssv_planner_date($_GET['date']??null);$plan=cssv_planner_plan($pdo,$user,$attempt,$date);if(!$plan)throw new OutOfBoundsException('No saved plan exists on this day.');cssv_json(['ok'=>true,'attempt'=>$a,'plan'=>$plan,'today'=>$today]);}
 if($view==='events'){$q=$pdo->prepare('SELECT id,event_type,unit_id,task_id,payload,occurred_at FROM attempt_planner_events WHERE user_id=? AND attempt_id=? ORDER BY occurred_at DESC,id DESC LIMIT 51 OFFSET '.$offset);$q->execute([$user,$attempt]);$rows=$q->fetchAll();foreach($rows as &$r){$r['payload']=json_decode($r['payload'],true,64,JSON_THROW_ON_ERROR);$r['occurred_at']=cssv_pro_iso($r['occurred_at']);}unset($r);cssv_json(['ok'=>true,'events'=>array_slice($rows,0,50),'has_more'=>count($rows)>50]);}
 if(!in_array($view,['plan','coverage','readiness','reviews'],true))throw new InvalidArgumentException('Choose a preparation view.');
 $c=cssv_planner_context($pdo,$user,$attempt,$today);$base=['ok'=>true,'attempt'=>$a,'settings'=>$settings,'today'=>$today,'active'=>$c['active'],'rules'=>cssv_planner_rules()];
 if($view==='coverage'){$d=cssv_planner_dimensions($c,$today);$rows=array_values($d['matrix']);if(isset($_GET['subject']))$rows=array_values(array_filter($rows,fn($r)=>$r['subject_id']===$_GET['subject']));cssv_json([...$base,'units'=>array_slice($rows,$offset,20),'has_more'=>count($rows)>$offset+20,'subjects'=>array_values(array_unique(array_map(fn($u)=>$u['subject_id'],$c['units']))),'coverage'=>$d['coverage']]);}
 if($view==='readiness'){$d=cssv_planner_dimensions($c,$today);unset($d['matrix']);cssv_json([...$base,'dimensions'=>$d]);}
 if($view==='reviews')cssv_json([...$base,'reviews'=>cssv_planner_reviews($pdo,$user,$attempt,$today,$c)]);
 $proposal=cssv_planner_proposal($pdo,$user,$attempt,$today,$c);$due=[];foreach($c['units'] as $u){$r=$c['progress'][$u['id']]??null;if($r&&!cssv_planner_source_changed($u,$r)&&$r['coverage']==='covered'&&$r['next_revision']&&$r['next_revision']<=$today)$due[]=['unit'=>$u,'due'=>$r['next_revision'],'last_studied'=>$r['last_studied'],'review_count'=>$r['review_count']];}
 usort($due,fn($a,$b)=>strcmp($a['due'].'/'.$a['unit']['id'],$b['due'].'/'.$b['unit']['id']));
 cssv_json([...$base,'plan'=>cssv_planner_plan($pdo,$user,$attempt,$today),'proposal'=>$proposal,'revision'=>array_slice($due,0,50),'revision_total'=>count($due),'overdue'=>$c['overdue'],'continue'=>['grammar'=>'/grammar-course?day='.($c['grammar']['state']['currentDay']??1).'&attempt='.$attempt,'precis'=>'/account/precis?attempt='.$attempt.'&view=course&day='.$c['precis']['current_day']]]);
}catch(Throwable $e){if($e instanceof InvalidArgumentException)cssv_fail($e->getMessage(),422,'planner_invalid');if($e instanceof OutOfBoundsException)cssv_fail($e->getMessage(),404,'planner_not_found');if($e instanceof DomainException)cssv_fail($e->getMessage(),409,'planner_conflict');error_log('CSSV planner failed: '.get_class($e));cssv_fail('Preparation could not be updated. Recover the saved action before trying again.',503,'planner_unavailable');}
