import { useSearchParams } from 'react-router'
import { AccountPage } from './shared'
import { featureNames, secondaryStyle, useLearning, type AiUsage } from '@/features/learning/api'
import { pakistanTime } from '@/features/membership/api'
export default function AiUsagePage() {
  const [params, setParams] = useSearchParams()
  const offset = Math.max(0, Number(params.get('offset')) || 0)
  const { data, error, refresh } = useLearning<AiUsage>(`ai-usage.php?offset=${offset}`)
  return <AccountPage title="AI Usage" intro="Your saved operation history and daily allowance accounting.">
    {!data ? <div role={error ? 'alert' : 'status'} className="rounded-xl border p-5">{error || 'Loading usage…'}{error && <button className={`${secondaryStyle} mt-3`} onClick={refresh}>Try again</button>}</div> : <div className="space-y-6">
      <p role="status" className="rounded-xl border bg-slate-50 p-5 text-sm leading-7">AI assistance is not open yet. The limits below are configured for future features. Reading, quizzes, planning and saving writing use no AI allowance.</p>
      <section><h2 className="text-lg font-semibold">Daily allowances · {data.date} (Pakistan)</h2><p className="mt-2 text-sm leading-7 text-slate-500">Used counts successful feedback. Pending work holds a reservation. Allowances reset at midnight Pakistan time; unused allowances do not roll over.</p><ul className="mt-4 divide-y rounded-xl border">{data.limits.map(row => <li key={row.feature} className="flex flex-wrap items-center justify-between gap-3 p-4 text-sm"><span className="font-semibold">{featureNames[row.feature] || row.feature}</span><span>{row.used} of {row.limit} used · {row.reserved} reserved</span></li>)}</ul><p className="mt-3 text-sm text-slate-500">Handwriting and OCR limits remain undecided and are not available.</p></section>
      <section><h2 className="text-lg font-semibold">Operation history</h2>{data.operations.length === 0 ? <p className="mt-3 rounded-xl border border-dashed p-5 text-sm text-slate-500">No AI operations recorded.</p> : <ul className="mt-3 divide-y rounded-xl border">{data.operations.map(op => <li key={op.id} className="space-y-3 p-4 text-sm"><p className="font-semibold">{featureNames[op.feature] || op.feature} · {op.state.replaceAll('_', ' ')}</p><p className="text-slate-500">{pakistanTime(op.created_at)} · allowance {op.accounting}</p>{op.state === 'unknown' && <p className="leading-7">The provider outcome is unresolved. Please check this operation before retrying; a timeout does not confirm failure.</p>}{op.result && <details><summary className="cursor-pointer font-semibold">Saved feedback</summary><p className="mt-3 whitespace-pre-wrap leading-7">{op.result.summary}</p>{op.result.findings.map((f, i) => <div key={`${f.code}:${i}`} className="mt-3 rounded-lg border p-3"><blockquote className="whitespace-pre-wrap break-words">{f.excerpt}</blockquote><p className="mt-2 leading-7">{f.explanation}</p><p className="mt-2 leading-7">Hint: {f.hint}</p></div>)}</details>}</li>)}</ul>}</section>
      <nav aria-label="AI usage pages" className="flex flex-wrap gap-3"><button disabled={offset === 0} onClick={() => setParams({ offset: String(Math.max(0, offset - 50)) })} className={secondaryStyle}>Previous page</button><button disabled={!data.has_more} onClick={() => setParams({ offset: String(offset + 50) })} className={secondaryStyle}>Next page</button><button onClick={refresh} className={secondaryStyle}>Refresh usage</button></nav>
    </div>}
  </AccountPage>
}
