import { Link, useSearchParams } from 'react-router'
import { ArrowLeft, ArrowRight, BookOpen, FilePenLine, History, ShieldCheck, Sparkles } from 'lucide-react'
import { useAccount } from '@/lib/accountContext'
import { AccountPage } from './shared'
import { useLearning } from '@/features/learning/api'
import { panelStyle, primaryStyle, secondaryStyle } from '@/features/handwriting/styles'
import { pakistanTime } from '@/features/membership/api'
import Composer from '@/features/expression/Composer'
import Review from '@/features/expression/Review'
import Comparison from '@/features/expression/Comparison'
import { grammarLink, type Overview, type Detail } from '@/features/expression/api'
function Workspace() {
 const [params, setParams] = useSearchParams(), writingId = params.get('writing'), versionId = params.get('version'), creating = params.get('new') === 'writing'
 const offset = Math.max(0, Number(params.get('offset')) || 0)
 const overview = useLearning<Overview>(`expression.php?offset=${offset}`)
 const detail = useLearning<Detail>(writingId ? `expression.php?writing_id=${encodeURIComponent(writingId)}${versionId ? `&version_id=${encodeURIComponent(versionId)}` : ''}` : undefined)
 function saved(writing: string, version: string) { setParams({ writing, version }); overview.refresh(); detail.refresh() }
 const error = overview.error || detail.error
 if (!overview.data || writingId && !detail.data) return <div role={error ? 'alert' : 'status'} className={panelStyle}>{error || 'Opening your Expression Lab…'}{error && <button className={`${secondaryStyle} mt-4`} onClick={() => { overview.refresh(); detail.refresh() }}>Try again</button>}</div>
 const data = overview.data, selected = detail.data
 return <div className="space-y-7">
  <section className="overflow-hidden rounded-3xl bg-slate-950 text-white"><div className="relative grid gap-6 p-6 sm:p-8 lg:grid-cols-[1fr_220px]"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_at_top_right,rgba(99,102,241,0.25),transparent_65%)]" aria-hidden="true" /><div className="relative"><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.18em] text-indigo-200"><FilePenLine className="h-4 w-4" aria-hidden="true" />English Expression Lab</p><h2 className="mt-4 text-3xl font-semibold leading-tight tracking-tight sm:text-4xl">Keep your voice.<br /><span className="text-indigo-200">Refine your writing.</span></h2><p className="mt-4 max-w-lg text-sm leading-7 text-slate-300">Work on clarity, grammar and structure through your own sentences and paragraphs. Understand the findings, write again and compare what changed.</p><p className="mt-5 flex items-center gap-2 text-xs text-slate-300"><ShieldCheck className="h-4 w-4 text-indigo-300" aria-hidden="true" />Your saved versions stay in your account after Pro expiry.</p></div><div className="relative self-center rounded-2xl border border-white/15 bg-white/5 p-5"><p className="text-xs text-slate-300">{data.configuration.enabled ? 'Feedback used today' : 'Feedback status'}</p>{data.configuration.enabled ? <><p className="mt-4 text-sm leading-7">Paragraphs: {data.usage.paragraph.used} of {data.usage.paragraph.limit}<br />Short expressions: {data.usage.sentence.used} of {data.usage.sentence.limit}</p><p className="mt-3 text-xs leading-6 text-slate-300">{data.usage.paragraph.reserved + data.usage.sentence.reserved} reserved · {data.date} (Pakistan)</p></> : <><p className="mt-4 text-xl font-semibold">Not open yet</p><p className="mt-2 text-xs leading-6 text-slate-300">Write, save and revise now. Evaluation opens after provider and launch checks.</p></>}</div></div><p className="flex flex-wrap items-center gap-x-3 gap-y-2 border-t border-white/10 bg-white/5 px-6 py-4 text-xs font-medium text-slate-300 sm:px-8"><span>Write</span><ArrowRight className="h-3 w-3" aria-hidden="true" /><span>Understand the findings</span><ArrowRight className="h-3 w-3" aria-hidden="true" /><span>Rewrite</span><ArrowRight className="h-3 w-3" aria-hidden="true" /><span>Compare</span></p></section>
  {(writingId || creating) && <button onClick={() => setParams({})} className={secondaryStyle}><ArrowLeft className="h-4 w-4" aria-hidden="true" />All expression writing</button>}
  {writingId && selected ? <><div className="grid items-start gap-6 lg:grid-cols-2"><Review key={selected.version.id} data={selected} refresh={() => { detail.refresh(); overview.refresh() }} onVersion={version => setParams({ writing: writingId, version })} /><Composer key={`${selected.writing.id}:${selected.version.id}`} overview={data} detail={selected} onSaved={saved} /></div><Comparison key={selected.version.id} writing={selected.writing} current={selected.version.id} evidenceKey={selected.operations.map(op => `${op.id}:${op.state}`).join(',')} /></> : creating ? <Composer overview={data} onSaved={saved} /> : <><section className={panelStyle}><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="flex items-center gap-3 text-xl font-semibold"><History className="h-5 w-5 text-indigo-600" aria-hidden="true" />Your writing history</h2><button onClick={() => setParams({ new: 'writing' })} className={primaryStyle}>New writing</button></div>{data.writing.length === 0 ? <p className="mt-5 rounded-2xl border border-dashed border-slate-200 bg-slate-50 p-7 text-sm leading-7 text-slate-500">No sentences or typed paragraphs saved yet. Start with your own wording; every saved revision keeps the earlier version.</p> : <ul className="mt-5 space-y-3">{data.writing.map(w => <li key={w.id}><button onClick={() => setParams({ writing: w.id })} className="flex min-h-20 w-full items-center justify-between gap-4 rounded-2xl border border-slate-200 p-4 text-left transition-colors hover:border-indigo-300 hover:bg-indigo-50/40"><span className="min-w-0"><span className="block break-words font-semibold">{w.title}</span><span className="mt-1 block text-xs leading-6 text-slate-500">{w.kind} · {w.version} saved version{w.version === 1 ? '' : 's'} · {pakistanTime(w.updated_at)}</span></span><ArrowRight className="h-4 w-4 shrink-0 text-indigo-600" aria-hidden="true" /></button></li>)}</ul>}<nav aria-label="Expression writing history" className="mt-5 flex flex-wrap gap-3"><button disabled={offset === 0} className={secondaryStyle} onClick={() => setParams({ offset: String(Math.max(0, offset - 50)) })}>Previous page</button><button disabled={!data.has_more} className={secondaryStyle} onClick={() => setParams({ offset: String(offset + 50) })}>Next page</button><button className={secondaryStyle} onClick={overview.refresh}>Refresh writing</button></nav></section>
   <section className={panelStyle}><h2 className="flex items-center gap-3 text-xl font-semibold"><Sparkles className="h-5 w-5 text-indigo-600" aria-hidden="true" />Writing error profile</h2><p className="mt-3 text-sm leading-7 text-slate-500">Based on up to {data.profile.sample_limit} different evaluated wordings in the past {data.profile.window_days} days, including confirmed handwriting feedback. {data.profile.reviewed_wordings} reviewed in this sample.</p>{data.profile.items.length === 0 ? <p className="mt-4 rounded-2xl bg-slate-50 p-5 text-sm leading-7">There is not enough reported evidence for a writing error profile yet. An empty profile does not mean every skill is mastered.</p> : <ul className="mt-4 divide-y divide-slate-200">{data.profile.items.map(item => <li key={item.code} className="flex flex-wrap items-center justify-between gap-3 py-4"><div><p className="text-sm font-semibold">{item.label}</p><p className="mt-1 text-xs leading-6 text-slate-500">Reported in {item.flagged_writings} different writing records · {item.reviewed_writings} reviewed</p></div><div className="flex flex-wrap items-center gap-3"><span className="rounded-full border border-slate-200 bg-slate-50 px-3 py-1 text-xs font-semibold">{item.state}</span><Link to={grammarLink(item.day)} className="inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-indigo-700"><BookOpen className="h-4 w-4" aria-hidden="true" />Practise</Link></div></li>)}</ul>}<details className="mt-5 text-xs leading-6 text-slate-500"><summary className="min-h-11 cursor-pointer font-semibold">How the evidence is interpreted</summary><p>{data.profile.basis}</p></details></section></>}
  <div className="flex flex-wrap gap-4 border-t border-slate-200 pt-5 text-sm"><Link to="/account/preparation" className="inline-flex min-h-11 items-center font-semibold text-indigo-700 hover:underline">My preparation and all writing</Link><Link to="/account/handwriting" className="inline-flex min-h-11 items-center font-semibold text-indigo-700 hover:underline">Handwritten paragraph</Link><Link to="/account/ai-usage" className="inline-flex min-h-11 items-center font-semibold text-indigo-700 hover:underline">AI usage and earlier results</Link></div>
 </div>
}
export default function ExpressionPage() { const { user } = useAccount(); return <AccountPage title="English Expression Lab" intro="Write, understand and revise through your own wording."><Workspace key={user?.id} /></AccountPage> }
