import { Link, useSearchParams } from 'react-router'
import { ArrowDownToLine, ArrowLeft, ArrowRight, Check, FilePenLine, History, ScanLine, ShieldCheck, Sparkles } from 'lucide-react'
import { useAccount } from '@/lib/accountContext'
import { AccountPage } from './shared'
import { useLearning } from '@/features/learning/api'
import { pakistanTime } from '@/features/membership/api'
import Upload from '@/features/handwriting/Upload'
import Detail from '@/features/handwriting/Transcription'
import { panelStyle, secondaryStyle } from '@/features/handwriting/styles'
import { stateNames, type HandwritingOverview, type HandwritingDetail } from '@/features/handwriting/api'
const stages = [{ name: 'Upload a page', note: 'One English paragraph', icon: ScanLine }, { name: 'Check the text', note: 'Your words, confirmed', icon: FilePenLine }, { name: 'Review feedback', note: 'Then practise a rewrite', icon: Sparkles }]
function WorkflowHeader({ data }: { data: HandwritingOverview | HandwritingDetail }) {
 const page = 'page' in data ? data.page : null
 const stage = !page || !page.transcription ? 0 : page.confirmed_version === page.transcription.version ? 2 : 1
 return <section className="overflow-hidden rounded-3xl bg-slate-950 text-white">
  <div className="relative grid gap-7 p-6 sm:p-8 lg:grid-cols-[1fr_220px]">
   <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_at_top_right,rgba(99,102,241,0.25),transparent_65%)]" aria-hidden="true" />
   <div className="relative"><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.18em] text-indigo-200"><FilePenLine className="h-4 w-4" aria-hidden="true" /> Handwriting workspace</p><h2 className="mt-4 max-w-xl text-3xl font-semibold leading-tight tracking-tight sm:text-4xl">From your page<br /><span className="text-indigo-200">to your next draft.</span></h2><p className="mt-4 max-w-lg text-sm leading-7 text-slate-300">Bring your handwritten paragraph into a focused workspace. Check the transcription, confirm your wording and use feedback to guide your rewrite.</p><p className="mt-5 flex items-center gap-2 text-xs text-slate-300"><ShieldCheck className="h-4 w-4 text-indigo-300" aria-hidden="true" /> Private to your account · Text and feedback stay in your history</p></div>
   <div className="relative self-center rounded-2xl border border-white/15 bg-white/5 p-5"><p className="text-xs font-medium text-slate-300">{data.configuration.enabled ? 'Today’s allowance' : 'Launch status'}</p>{data.configuration.enabled ? <><div className="mt-4 flex items-baseline gap-1"><span className="text-4xl font-semibold tracking-tight">{Math.max(0, data.usage.handwriting.limit - data.usage.handwriting.used - data.usage.handwriting.reserved)}</span><span className="text-sm text-slate-300">feedback left</span></div><p className="mt-3 text-xs leading-6 text-slate-300">{data.usage.handwriting_extract.accepted} of {data.usage.handwriting_extract.limit} extraction attempts accepted<br />{data.usage.handwriting.used} feedback used · {data.usage.handwriting.reserved} reserved</p><p className="mt-3 border-t border-white/10 pt-3 text-xs text-slate-400">{data.date} · Pakistan</p></> : <><p className="mt-4 text-xl font-semibold">Not open yet</p><p className="mt-2 text-xs leading-6 text-slate-300">Preview a page locally. Uploads and assistance will open after launch checks.</p></>}</div>
  </div>
  <ol aria-label="Handwriting workflow" className="grid grid-cols-3 border-t border-white/10 bg-white/5">{stages.map((item, index) => <li key={item.name} aria-current={stage === index ? 'step' : undefined} className={`min-w-0 border-r border-white/10 px-3 py-5 last:border-r-0 sm:px-6 ${stage === index ? 'bg-indigo-400/10' : ''}`}><div className="flex flex-col gap-3 sm:flex-row sm:items-center"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-xl border text-sm ${index < stage ? 'border-indigo-300/40 bg-indigo-300/15 text-indigo-200' : index === stage ? 'border-indigo-300 bg-indigo-300 text-slate-950' : 'border-white/20 text-slate-400'}`}>{index < stage ? <Check className="h-4 w-4" aria-hidden="true" /> : index + 1}</span><div><p className={`text-xs font-semibold sm:text-sm ${index === stage ? 'text-white' : 'text-slate-300'}`}>{item.name}</p><p className="mt-1 hidden text-xs text-slate-400 sm:block">{item.note}</p></div></div></li>)}</ol>
 </section>
}
function Workspace() {
 const [params, setParams] = useSearchParams(), id = params.get('page')
 const offset = Math.max(0, Number(params.get('offset')) || 0)
 const { data, error, refresh } = useLearning<HandwritingOverview | HandwritingDetail>(id ? `handwriting.php?page_id=${encodeURIComponent(id)}` : `handwriting.php?offset=${offset}`)
 if (!data) return <div role={error ? 'alert' : 'status'} className={panelStyle}>{error || 'Loading your handwriting workspace…'}{error && <button onClick={refresh} className={`${secondaryStyle} mt-3`}>Try again</button>}</div>
 return <div className="space-y-7">
  <WorkflowHeader data={data} />
  {'page' in data ? <><button className={secondaryStyle} onClick={() => setParams({})}><ArrowLeft className="h-4 w-4" aria-hidden="true" /> All handwritten pages</button><Detail key={data.page.id} data={data} refresh={refresh} /></> : <><Upload data={data} onSaved={page => setParams({ page })} /><section className={panelStyle}><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="flex items-center gap-3 text-xl font-semibold tracking-tight"><History className="h-5 w-5 text-indigo-600" aria-hidden="true" /> Saved handwritten pages</h2><button className={secondaryStyle} onClick={refresh}>Refresh pages</button></div>{data.pages.length === 0 ? <div className="mt-5 rounded-2xl border border-dashed border-slate-200 bg-slate-50/70 p-8 text-center"><ArrowDownToLine className="mx-auto h-7 w-7 text-slate-400" aria-hidden="true" /><p className="mt-4 text-sm font-semibold text-slate-700">No handwritten pages saved.</p><p className="mt-2 text-sm leading-6 text-slate-500">Your saved pages, confirmed text and feedback will appear here.</p></div> : <ul className="mt-5 grid gap-3">{data.pages.map(page => <li key={page.id}><button onClick={() => setParams({ page: page.id })} className="group flex min-h-20 w-full items-center gap-4 rounded-2xl border border-slate-200 p-4 text-left transition-colors hover:border-indigo-300 hover:bg-indigo-50/40 focus-visible:outline focus-visible:outline-2 focus-visible:outline-indigo-600"><span className="hidden h-11 w-11 shrink-0 place-items-center rounded-xl bg-indigo-50 text-indigo-600 sm:grid"><FilePenLine className="h-5 w-5" aria-hidden="true" /></span><span className="min-w-0 flex-1"><span className="block break-words font-semibold text-slate-900">{page.title}</span><span className="mt-1 block text-xs leading-6 text-slate-500">{stateNames[page.state] || page.state} · {pakistanTime(page.created_at)}</span></span><ArrowRight className="h-4 w-4 shrink-0 text-slate-400 group-hover:text-indigo-600" aria-hidden="true" /></button></li>)}</ul>}<nav aria-label="Handwriting history pages" className="mt-5 flex flex-wrap gap-3"><button disabled={offset === 0} className={secondaryStyle} onClick={() => setParams({ offset: String(Math.max(0, offset - 50)) })}>Previous page</button><button disabled={!data.has_more} className={secondaryStyle} onClick={() => setParams({ offset: String(offset + 50) })}>Next page</button></nav></section></>}
  <div className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-200 pt-5 text-xs leading-6 text-slate-500"><p>Reading saved work, corrections and confirmation use no provider allowance.</p><Link to="/account/preparation" className="inline-flex min-h-11 items-center gap-2 font-semibold text-indigo-700 hover:underline">My preparation and writing history <ArrowRight className="h-4 w-4" aria-hidden="true" /></Link></div>
 </div>
}
export default function HandwritingPage() { const { user } = useAccount(); return <AccountPage title="Handwritten Paragraph" intro="Your writing, with a clearer path to the next draft."><Workspace key={user?.id} /></AccountPage> }
