// End-to-end server rules for the MPT examination system (Sections 8, 16, 21, 22),
// run against the real PHP API and a disposable MySQL database.
import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import { randomBytes } from 'node:crypto'
if (process.env.CI !== 'true' || process.env.CSSV_DB_NAME !== 'cssvista_briefing_test') throw new Error('Disposable CI database required')

const base = 'http://localhost:4173/api/mpt/'
const fixture = (...args) => JSON.parse(execFileSync('php', ['tests/mpt/fixtures.php', ...args.map(String)], { encoding: 'utf8' }))
const bodies = []
async function call(user, path, body, extra = {}) {
  const headers = { Accept: 'application/json', 'User-Agent': 'CSSVistaMptTest', ...extra }
  if (user) headers.Cookie = `cssv_session=${user.session}; cssv_csrf=${user.csrf}`
  if (body !== undefined) {
    headers['Content-Type'] = 'application/json'
    if (!('X-CSRF-Token' in headers) && user) headers['X-CSRF-Token'] = user.csrf
  }
  const response = await fetch(base + path, { method: body === undefined ? 'GET' : 'POST', headers, body: body === undefined ? undefined : JSON.stringify(body) })
  const text = await response.text()
  bodies.push({ user: user?.id, path, text })
  let data = {}
  try { data = JSON.parse(text) } catch { /* non-JSON */ }
  return { status: response.status, data, text, headers: response.headers }
}
const clientId = () => randomBytes(18).toString('base64url')
const within = (actualIso, expectedMs, toleranceMs, label) => assert.ok(Math.abs(Date.parse(actualIso) - expectedMs) <= toleranceMs, `${label}: ${actualIso}`)
const step = (name) => console.log(`- ${name}`)

const [A, B, C, D, E] = fixture('users', 5, 'mpt')
// The service runs with CSSV_MPT_APPLICATION_FLOW=on here; off/pilot are covered by tests/mpt/flag.php.

step('feature flag and authentication')
assert.equal((await call(null, 'config.php')).data.enabled, true)
assert.equal((await call(null, 'dashboard.php')).status, 401)
assert.equal((await call(null, 'apply.php', { mock: 'mpt-mock-001', declaration: true })).status, 401)
assert.equal((await call(A, 'config.php')).data.enabled, true)

step('application window and atomic apply')
const m1 = fixture('mock', 120)
const anonymous = await call(null, 'mocks.php')
assert.equal(anonymous.data.mocks.find((card) => card.mock.slug === m1.slug).state.phase, 'LOGIN_REQUIRED')
let read = await call(A, `application.php?mock=${m1.slug}`)
assert.equal(read.status, 200, read.text)
assert.equal(read.data.state.phase, 'APPLICATIONS_OPEN')
assert.equal(read.data.mock.fee, 'FREE')
assert.ok(read.headers.get('cache-control').includes('no-store'))
assert.equal((await call(A, 'apply.php', { mock: m1.slug })).data.error, 'declaration_required')
assert.equal((await call(A, 'apply.php', { mock: m1.slug, declaration: true }, { 'X-CSRF-Token': 'wrong' })).status, 403)
assert.equal((await call(A, 'apply.php', { mock: m1.slug, declaration: true }, { Origin: 'https://evil.invalid' })).status, 403)
const beforeApply = Date.now()
const applied = await call(A, 'apply.php', { mock: m1.slug, declaration: true }, { 'Idempotency-Key': 'test-key-1' })
assert.equal(applied.status, 201, applied.text)
assert.equal(applied.data.already_applied, false)
assert.equal(applied.data.state.phase, 'ROLL_NUMBER_PENDING')
assert.equal(applied.data.application.roll_number, null, 'roll number must not be returned before its reveal time')
assert.match(applied.data.application.application_code, /^MPTA-\d{3,}-[2-9A-HJKMNP-Z]{6}$/)
within(applied.data.application.roll_number_visible_at, beforeApply + 600_000, 5000, 'reveal 10 minutes after applying')
const codeA = applied.data.application.application_code
const rollA = fixture('roll', m1.slug, A.id).roll_number
assert.match(rollA, /^[1-9]\d{5}$/)
const again = await call(A, 'apply.php', { mock: m1.slug, declaration: true })
assert.equal(again.status, 200)
assert.equal(again.data.already_applied, true)
assert.equal(again.data.application.application_code, codeA, 'double apply returns the same application')
assert.equal(fixture('table', `SELECT COUNT(*) FROM mpt_applications WHERE application_code='${codeA}'`).value, 1)
assert.equal((await call(A, `application.php?code=${codeA}`)).data.application.roll_number, null)
assert.equal((await call(B, `application.php?code=${codeA}`)).status, 404, "another candidate's application is a 404")
const earlyVerify = await call(A, 'verify.php', { mock: m1.slug, roll_number: rollA })
assert.equal(earlyVerify.data.error, 'roll_not_linked', 'an unrevealed roll number cannot be verified')
for (const entry of bodies) assert.ok(!entry.text.includes(rollA), `roll number leaked early by ${entry.path}`)

step('roll number reveal after ten minutes')
fixture('travel', m1.slug, 11)
read = await call(A, `application.php?code=${codeA}`)
assert.equal(read.data.application.roll_number, rollA)
assert.equal(read.data.state.phase, 'SLOT_RESERVED')
await call(A, `application.php?code=${codeA}`)
assert.equal(fixture('events', m1.slug, 'ROLL_NUMBER_ISSUED').count, 1, 'first reveal is logged once')
const notOpen = await call(A, 'verify.php', { mock: m1.slug, roll_number: rollA })
assert.equal(notOpen.data.error, 'entry_not_open')
assert.match(notOpen.data.message, /Entry opens at \d{1,2}:\d{2} [AP]M PKT/)

const appliedB = await call(B, 'apply.php', { mock: m1.slug, declaration: true })
assert.equal(appliedB.status, 201)
const appliedD = await call(D, 'apply.php', { mock: m1.slug, declaration: true })
assert.equal(appliedD.status, 201)
const rollB = fixture('roll', m1.slug, B.id).roll_number
assert.notEqual(rollA, rollB)

step('entrance gate: late start after exam opens')
fixture('travel', m1.slug, 117) // exam opened 8 minutes ago
const typo = String((Number(rollA[5]) + 1) % 10)
const wrongDigit = await call(A, 'verify.php', { mock: m1.slug, roll_number: rollA.slice(0, 5) + typo })
assert.equal(wrongDigit.status, 422)
assert.equal(wrongDigit.data.error, 'roll_format')
assert.equal(wrongDigit.data.message, 'Please check your Roll Number — one digit looks wrong.')
const someoneElse = await call(A, 'verify.php', { mock: m1.slug, roll_number: rollB })
const unknown = await call(A, 'verify.php', { mock: m1.slug, roll_number: '482918' === rollA || '482918' === rollB ? '123455' : '482918' })
assert.equal(someoneElse.data.error, 'roll_not_linked')
assert.equal(someoneElse.status, unknown.status)
assert.equal(someoneElse.data.message, unknown.data.message, "another candidate's roll and an unknown roll are indistinguishable")
const verified = await call(A, 'verify.php', { mock: m1.slug, roll_number: `${rollA.slice(0, 3)} ${rollA.slice(3)}` })
assert.equal(verified.status, 200, verified.text)
assert.equal(verified.data.minutes_late, 8)
assert.ok(Math.abs(verified.data.time_allowance_seconds - 192 * 60) <= 5, `late entrant gets duration − 8 min: ${verified.data.time_allowance_seconds}`)
assert.equal(verified.data.candidate.roll_number, rollA)
assert.equal(verified.data.resume, false)
assert.deepEqual(verified.data.sections.map((s) => s.label), ['Islamic Studies', 'Urdu', 'English', 'General Abilities', 'General Knowledge'])
assert.equal(verified.data.sections.reduce((sum, s) => sum + s.count, 0), 200)

step('start: token bound to the candidate, paper without keys')
const clientA1 = clientId()
assert.equal((await call(A, 'start.php', { client_id: clientA1 })).data.error, 'verification_required')
assert.equal((await call(B, 'start.php', { verification_token: verified.data.verification_token, client_id: clientId() })).data.error, 'verification_required')
const started = await call(A, 'start.php', { verification_token: verified.data.verification_token, client_id: clientA1 })
assert.equal(started.status, 201, started.text)
assert.equal(started.data.paper.length, 200)
assert.deepEqual(Object.keys(started.data.paper[0]).sort(), ['o', 'p', 'q', 'section'])
assert.ok(!/"(?:a|correct|correct_index|answer|explanation|question_id|id)":/.test(started.text), 'the paper must not carry answer keys or bank ids')
assert.equal(started.data.attempt.expires_at, verified.data.mock.exam_end_at, 'every attempt ends at exam_end_at')
const doubleTap = await call(A, 'start.php', { verification_token: verified.data.verification_token, client_id: clientA1 })
assert.equal(doubleTap.status, 200)
assert.equal(doubleTap.data.resumed, true)
assert.equal(fixture('table', `SELECT COUNT(*) FROM mpt_attempts WHERE mock_id='${m1.id}'`).value, 1, 'double start creates one attempt')

step('autosave, stale saves, resume and device lock')
const key = fixture('key', m1.slug)
const answers = { 1: key[1], 2: (key[2] + 1) % 4, 3: key[3], 4: key[4], 5: (key[5] + 1) % 4 }
let saved = await call(A, 'save.php', { mock: m1.slug, client_id: clientA1, save_version: 1, current_position: 5, changes: Object.entries(answers).slice(0, 3).map(([p, o]) => ({ p: Number(p), o })) })
assert.equal(saved.status, 200, saved.text)
assert.ok(saved.data.remaining_seconds > 0)
const stale = await call(A, 'save.php', { mock: m1.slug, client_id: clientA1, save_version: 1, changes: [{ p: 1, o: 0 }] })
assert.equal(stale.status, 409)
assert.equal(stale.data.error, 'stale_save')
assert.equal((await call(A, 'save.php', { mock: m1.slug, client_id: clientA1, save_version: 2, changes: [{ p: 999, o: 1 }] })).status, 422)
assert.equal((await call(A, 'save.php', { mock: m1.slug, client_id: clientA1, save_version: 2, changes: [{ p: 1, o: 7 }] })).status, 422)
saved = await call(A, 'save.php', { mock: m1.slug, client_id: clientA1, save_version: 2, changes: Object.entries(answers).slice(3).map(([p, o]) => ({ p: Number(p), o })) })
assert.equal(saved.status, 200)
const resumed = await call(A, `attempt.php?mock=${m1.slug}&client_id=${clientA1}`)
assert.equal(resumed.status, 200)
assert.deepEqual(resumed.data.answers, Object.fromEntries(Object.entries(answers).map(([p, o]) => [p, o])))
assert.equal(resumed.data.attempt.save_version, 2)
assert.equal(resumed.data.attempt.current_position, 5)
const clientA2 = clientId()
assert.equal((await call(A, `attempt.php?mock=${m1.slug}&client_id=${clientA2}`)).data.error, 'device_conflict')
assert.equal((await call(A, 'save.php', { mock: m1.slug, client_id: clientA2, save_version: 3, changes: [] })).data.error, 'device_conflict')
assert.equal((await call(B, `attempt.php?mock=${m1.slug}&client_id=${clientA1}`)).status, 404, "another candidate cannot open this attempt")
const reverify = await call(A, 'verify.php', { mock: m1.slug, roll_number: rollA })
assert.equal(reverify.data.resume, true)
const takeover = await call(A, 'start.php', { verification_token: reverify.data.verification_token, client_id: clientA2 })
assert.equal(takeover.status, 200)
assert.equal(takeover.data.resumed, true)
assert.equal(fixture('events', m1.slug, 'DEVICE_TAKEOVER').count, 1)
assert.equal((await call(A, 'save.php', { mock: m1.slug, client_id: clientA1, save_version: 3, changes: [] })).data.error, 'device_conflict', 'the old device is locked out')

step('late applicant gets the roll number instantly')
const appliedC = await call(C, 'apply.php', { mock: m1.slug, declaration: true })
assert.equal(appliedC.status, 201)
assert.equal(appliedC.data.state.phase, 'ENTRY_OPEN')
const rollC = appliedC.data.application.roll_number
assert.equal(rollC, fixture('roll', m1.slug, C.id).roll_number)
const verifiedC = await call(C, 'verify.php', { mock: m1.slug, roll_number: rollC })
const clientC = clientId()
assert.equal((await call(C, 'start.php', { verification_token: verifiedC.data.verification_token, client_id: clientC })).status, 201)
await call(C, 'save.php', { mock: m1.slug, client_id: clientC, save_version: 1, changes: [{ p: 1, o: key[1] }, { p: 2, o: key[2] }] })

step('manual submit is scored on the server and idempotent')
const submitted = await call(A, 'submit.php', { mock: m1.slug, client_id: clientA2 })
assert.equal(submitted.status, 200, submitted.text)
assert.equal(submitted.data.state.phase, 'RESULT_AVAILABLE')
assert.equal(submitted.data.result.correct, 3)
assert.equal(submitted.data.result.incorrect, 2)
assert.equal(submitted.data.result.unanswered, 195)
assert.equal(submitted.data.result.score, 3)
assert.equal(submitted.data.result.total_marks, 200)
assert.equal(submitted.data.result.percentage, 1.5)
assert.equal(submitted.data.result.accuracy, 60)
assert.equal(submitted.data.result.rank, null, 'rank waits for the window to end')
assert.equal(submitted.data.result.review_available, false, 'answer review waits for exam_end_at')
assert.equal(submitted.data.result.subjects.reduce((sum, s) => sum + s.questions, 0), 200)
const twice = await call(A, 'submit.php', { mock: m1.slug, client_id: clientA2 })
assert.equal(twice.data.result.submitted_at, submitted.data.result.submitted_at)
assert.equal(fixture('events', m1.slug, 'SUBMITTED').count, 1)
assert.equal((await call(A, 'verify.php', { mock: m1.slug, roll_number: rollA })).data.error, 'already_completed')
assert.equal((await call(A, `review.php?code=${codeA}`)).status, 403)
assert.equal((await call(B, `result.php?code=${codeA}`)).status, 404)

step('entry closes ten minutes after the exam starts')
fixture('travel', m1.slug, 3)
assert.equal((await call(D, 'verify.php', { mock: m1.slug, roll_number: fixture('roll', m1.slug, D.id).roll_number })).data.error, 'entry_closed')
assert.equal((await call(E, 'apply.php', { mock: m1.slug, declaration: true })).data.error, 'applications_closed')
assert.equal((await call(D, `application.php?mock=${m1.slug}`)).data.state.phase, 'ABSENT')

step('sweeper auto-submits, marks absences and ranks')
fixture('set', m1.slug, 'rank_min_candidates', 1)
fixture('travel', m1.slug, 200)
const sweep = fixture('sweep')
assert.ok(sweep.auto_submitted >= 1, JSON.stringify(sweep))
const resultC = await call(C, `result.php?code=${appliedC.data.application.application_code}`)
assert.equal(resultC.data.result.submit_reason, 'TIME_EXPIRED')
assert.equal(resultC.data.result.correct, 2)
assert.equal(fixture('events', m1.slug, 'MARKED_ABSENT').count, 2, 'B and D applied but never started')
const finalA = await call(A, `result.php?code=${codeA}`)
assert.deepEqual(finalA.data.result.rank, { position: 1, candidates: 2, percentile: 50 }, 'A (3) outranks C (2)')
assert.equal(finalA.data.result.review_available, true)
const review = await call(A, `review.php?code=${codeA}`)
assert.equal(review.status, 200)
assert.equal(review.data.questions[0].correct, key[1])
assert.equal(review.data.questions[1].selected, answers[2])
const dashboard = await call(A, 'dashboard.php')
assert.equal(dashboard.data.stats.attempts_completed, 1)
assert.equal(dashboard.data.latest.application_code, codeA)
assert.equal(dashboard.data.trend.label, null, 'no trend label before three completed mocks')
const historyD = await call(D, 'history.php')
assert.equal(historyD.data.rows[0].phase, 'ABSENT')
assert.equal((await call(D, 'dashboard.php')).data.stats.attempts_completed, 0, 'absences never count as a zero score')
const perf = await call(A, 'performance.php')
assert.equal(perf.data.series.length, 1)
assert.equal(perf.data.strongest, null, 'no strongest subject without enough answered questions')

step('papers never repeat across mocks')
const m2 = fixture('mock', 90, 1)
assert.equal(fixture('table', `SELECT COUNT(*) FROM mpt_mock_questions WHERE mock_id='${m2.id}'`).value, 200)
const overlap = execFileSync('php', ['-r', `$pdo=new PDO('mysql:host=${process.env.CSSV_DB_HOST};port=${process.env.CSSV_DB_PORT};dbname=${process.env.CSSV_DB_NAME}','${process.env.CSSV_DB_USER}','${process.env.CSSV_DB_PASSWORD}');echo $pdo->query("SELECT COUNT(*) FROM mpt_mock_questions a JOIN mpt_mock_questions b ON a.question_id=b.question_id WHERE a.mock_id='${m1.id}' AND b.mock_id='${m2.id}'")->fetchColumn();`], { encoding: 'utf8' })
assert.equal(overlap.trim(), '0')

step('capacity race: 50 concurrent applies for the last slot')
const crowd = fixture('users', 50, 'crowd')
const results = await Promise.all(crowd.map((user) => call(user, 'apply.php', { mock: m2.slug, declaration: true })))
assert.equal(results.filter((r) => r.status === 201).length, 1, results.map((r) => r.status).join(','))
assert.equal(results.filter((r) => r.data.error === 'slots_full').length, 49)
assert.equal(fixture('table', `SELECT COUNT(*) FROM mpt_applications WHERE mock_id='${m2.id}'`).value, 1)
const winner = crowd[results.findIndex((r) => r.status === 201)]
assert.equal((await call(winner, `application.php?mock=${m2.slug}`)).data.state.phase, 'ROLL_NUMBER_PENDING')
assert.equal((await call(crowd.find((u) => u !== winner), `application.php?mock=${m2.slug}`)).data.state.phase, 'SLOTS_FULL')

step('withdraw frees capacity; re-apply keeps the roll number')
const withdrawn = await call(winner, 'withdraw.php', { code: (await call(winner, `application.php?mock=${m2.slug}`)).data.application.application_code })
assert.equal(withdrawn.status, 200, withdrawn.text)
assert.equal(withdrawn.data.state.phase, 'APPLICATIONS_OPEN')
const rollWinner = fixture('roll', m2.slug, winner.id).roll_number
const reapplied = await call(winner, 'apply.php', { mock: m2.slug, declaration: true })
assert.equal(reapplied.status, 201)
assert.equal(fixture('roll', m2.slug, winner.id).roll_number, rollWinner)
fixture('travel', m2.slug, 91)
assert.equal((await call(winner, 'withdraw.php', { code: reapplied.data.application.application_code })).data.error, 'withdraw_closed')

step('roll verification brute-force lockout')
const m3 = fixture('mock', 0)
await call(E, 'apply.php', { mock: m3.slug, declaration: true })
let lastStatus = 0
for (let i = 0; i < 6; i += 1) {
  const guess = String(100000 + Math.floor(Math.random() * 899999))
  lastStatus = (await call(E, 'verify.php', { mock: m3.slug, roll_number: guess })).status
}
assert.equal(lastStatus, 429, 'sixth failed guess within ten minutes is rate limited')

step('daily schedule: 15:00 and 22:30 PKT, created idempotently')
const schedule = fixture('autoschedule', '2031-03-10T09:30:00.000Z') // 14:30 PKT
const keys = schedule.mocks.map((m) => m.schedule_key)
assert.ok(keys.includes('daily-2031-03-10-1500'), keys.join(','))
assert.ok(keys.includes('daily-2031-03-10-2230'), keys.join(','))
assert.equal(new Set(keys).size, keys.length)
const afternoon = schedule.mocks.find((m) => m.schedule_key === 'daily-2031-03-10-1500')
assert.equal(afternoon.exam_open_at.slice(0, 16), '2031-03-10 10:00')
assert.equal(afternoon.application_close_at.slice(0, 16), '2031-03-10 10:10')
assert.equal(afternoon.exam_end_at.slice(0, 16), '2031-03-10 13:20')
assert.equal(afternoon.application_open_at.slice(0, 16), '2031-03-09 10:00')
assert.equal(afternoon.status, 'PUBLISHED')

console.log('MPT examination server rules verified.')
