<?php
declare(strict_types=1);
require __DIR__.'/../../public/api/_tutor_context.php';require __DIR__.'/../../public/api/_tutor_schema.php';
$n=0;function check(bool $v,string $why):void{global $n;$n++;if(!$v)throw new RuntimeException($why);}function reject(callable $f):void{global $n;try{$f();}catch(InvalidArgumentException){$n++;return;}throw new RuntimeException('Invalid tutor data accepted.');}
$contexts=cssv_tutor_static_contexts();check(count(array_filter($contexts,fn($c)=>$c['category']==='grammar'))===126,'Grammar rules missing');
foreach($contexts as $c){check(mb_strlen($c['text'])<=16000&&$c['text']!=='','Unbounded/empty context');check(str_starts_with($c['return_path'],'/')&&!str_starts_with($c['return_path'],'//'),'Arbitrary return URL');}
foreach(['precis:2','precis:18','precis:20','precis:appendix-c'] as $id)check(!isset($contexts[$id]),'Official-pending/model chapter exposed through tutor');
check(str_contains($contexts['maths:percentage']['text'],'25%')&&str_contains($contexts['maths:percentage']['text'],'16.'),'Deterministic percent changed');check(str_contains($contexts['maths:mean']['text'],'mean is 6.'),'Mean changed');check(str_contains($contexts['maths:ratio']['text'],'2:3'),'Ratio changed');
foreach(['Please mark my full answer out of 20.','Generate a complete answer for this question.','Evaluate my essay.','Please replace my mentor marks.','میرے مکمل جواب کی جانچ کریں','Write my 20-mark answer.'] as $q)reject(fn()=>cssv_tutor_question($q));
foreach(['How does subject–verb agreement work?','Why does this précis need to preserve qualification?','How do I calculate a percentage change?'] as $q)check(cssv_tutor_question($q)===$q,'Conceptual question blocked');
reject(fn()=>cssv_tutor_question(str_repeat('word ',151)));reject(fn()=>cssv_tutor_question('abc'));
$input=['context'=>$contexts['grammar:5:0'],'question'=>'How does this rule work?','intent'=>'explain','previous'=>null,'attempt'=>['id'=>'TEST-ID-MUST-NOT-BE-SENT','stage'=>'starting','daily_minutes'=>120]];
$result=['status'=>'answered','explanation'=>'The subject determines the form of the verb.','steps'=>['Find the subject first.'],'check_question'=>'Which word names the subject?','citations'=>[['quote'=>mb_substr($input['context']['text'],0,80)]],'limitation'=>''];check(cssv_tutor_result($result,$input)===$result,'Anchored teaching rejected');
foreach([['citations'=>[]],['citations'=>[['quote'=>'A fabricated excerpt that is not in the source.']]],['explanation'=>'Your score is 12 marks.'],['explanation'=>'Go to https://invented.example.invalid/'],['steps'=>['a','b','c','d']],['marks'=>20],['status'=>'official']] as $bad)reject(fn()=>cssv_tutor_result([...$result,...$bad],$input));
$uncertain=['status'=>'needs_context','explanation'=>'The source does not define that concept.','steps'=>[],'check_question'=>'','citations'=>[],'limitation'=>'Choose additional reviewed source material.'];check(cssv_tutor_result($uncertain,$input)['status']==='needs_context','Honest insufficient-context reply rejected');reject(fn()=>cssv_tutor_result([...$uncertain,'steps'=>['Invent a definition.']],$input));
$redirect=[...$uncertain,'status'=>'redirect','explanation'=>'I cannot mark an essay or replace mentor marks.','limitation'=>'Take a full answer to your human mentor.'];check(cssv_tutor_result($redirect,$input)['status']==='redirect','Honest refusal was blocked');reject(fn()=>cssv_tutor_result([...$redirect,'explanation'=>'Your score is 18 marks.'],$input));
$row=['id'=>'TEST','headline'=>'TEST ONLY headline','publication_date'=>'2001-02-03','content'=>json_encode(['summary'=>'TEST ONLY conceptual source','sources'=>[['publisher'=>'TEST ONLY','url'=>'https://user:password@example.invalid/']]])];try{cssv_tutor_published_context($row);throw new RuntimeException('Credential URL accepted');}catch(OutOfBoundsException){$n++;}
$payload=cssv_tutor_payload(['model'=>'gpt-6-luna'],$input);check($payload['store']===false&&!isset($payload['tools']),'Provider persistence/tools enabled');check(!str_contains(json_encode($payload),'TEST-ID-MUST-NOT-BE-SENT'),'Private attempt identity sent to provider');
check(cssv_tutor_hash(['b'=>['z'=>2,'x'=>1],'a'=>0])===cssv_tutor_hash(['a'=>0,'b'=>['x'=>1,'z'=>2]]),'MySQL JSON key order changed snapshot identity');check(cssv_tutor_hash(['a'=>'first'])!==cssv_tutor_hash(['a'=>'changed']),'Content hash failed');
foreach(cssv_tutor_schema_statements() as $sql)check(str_contains(file_get_contents(__DIR__.'/../../server/sql/019_scoped_tutor.sql'),$sql.';'),'Migration parity mismatch');
echo "PASS: $n scoped tutor source/model isolation, deterministic Maths, excluded marking, strict citations/output, minimal provider context, canonical snapshot and schema assertions.\n";
