-- VISTA Exam Intelligence: normalized, private question-attempt history.
-- Additive migration. Existing progress payloads and student records remain unchanged.

create table if not exists public.question_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_key text not null,
  question_id text not null,
  category text not null default '',
  topic text,
  subtopic text,
  mode text,
  difficulty text,
  selected_option integer check (selected_option between -1 and 20),
  correct boolean not null,
  attempted_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique (user_id, event_key)
);

create index if not exists question_attempts_user_time_idx
  on public.question_attempts (user_id, attempted_at desc);
create index if not exists question_attempts_user_category_idx
  on public.question_attempts (user_id, category, attempted_at desc);
create index if not exists question_attempts_user_topic_idx
  on public.question_attempts (user_id, topic, attempted_at desc)
  where topic is not null;
create index if not exists question_attempts_user_incorrect_idx
  on public.question_attempts (user_id, attempted_at desc)
  where not correct;

alter table public.question_attempts enable row level security;

drop policy if exists "Students read their own question attempts" on public.question_attempts;
create policy "Students read their own question attempts"
on public.question_attempts for select to authenticated
using ((select auth.uid()) = user_id or public.is_css_vista_admin());

drop policy if exists "Students create their own question attempts" on public.question_attempts;
create policy "Students create their own question attempts"
on public.question_attempts for insert to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Students delete their own question attempts" on public.question_attempts;
create policy "Students delete their own question attempts"
on public.question_attempts for delete to authenticated
using ((select auth.uid()) = user_id);

revoke all on table public.question_attempts from anon;
grant select, insert, delete on table public.question_attempts to authenticated;
grant usage, select on sequence public.question_attempts_id_seq to authenticated;

analyze public.question_attempts;
