-- CSS Vista production student records and role-based administration.
-- Run after 202607260001_student_accounts.sql.

create extension if not exists pgcrypto;

create table if not exists public.student_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_seen_at timestamptz
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

create table if not exists public.student_activity (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_key text not null,
  activity_type text not null,
  label text not null default '',
  path text,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique (user_id, event_key)
);

create index if not exists student_activity_user_time_idx
  on public.student_activity (user_id, occurred_at desc);

create table if not exists public.quiz_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  attempt_key text not null,
  quiz_type text not null,
  category text not null default '',
  score integer not null check (score >= 0),
  total integer not null check (total > 0 and score <= total),
  metadata jsonb not null default '{}'::jsonb,
  completed_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique (user_id, attempt_key)
);

create index if not exists quiz_attempts_user_time_idx
  on public.quiz_attempts (user_id, completed_at desc);

create or replace function public.is_css_vista_admin(check_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select check_user_id = (select auth.uid()) and exists (
    select 1 from public.admin_users
    where user_id = (select auth.uid())
  );
$$;

revoke all on function public.is_css_vista_admin(uuid) from public;
grant execute on function public.is_css_vista_admin(uuid) to authenticated;

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists student_profiles_touch_updated_at on public.student_profiles;
create trigger student_profiles_touch_updated_at
before update on public.student_profiles
for each row execute function public.touch_updated_at();

create or replace function public.create_css_vista_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.student_profiles (user_id, display_name, avatar_url)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    new.raw_user_meta_data ->> 'avatar_url'
  )
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists css_vista_profile_on_signup on auth.users;
create trigger css_vista_profile_on_signup
after insert on auth.users
for each row execute function public.create_css_vista_profile();

-- Trigger-only function: never expose it as a Data API RPC.
revoke all on function public.create_css_vista_profile() from public, anon, authenticated;

insert into public.student_profiles (user_id, display_name, avatar_url)
select
  id,
  coalesce(raw_user_meta_data ->> 'full_name', ''),
  raw_user_meta_data ->> 'avatar_url'
from auth.users
on conflict (user_id) do nothing;

alter table public.student_profiles enable row level security;
alter table public.admin_users enable row level security;
alter table public.student_activity enable row level security;
alter table public.quiz_attempts enable row level security;

drop policy if exists "Students read their own profile" on public.student_profiles;
create policy "Students read their own profile"
on public.student_profiles for select to authenticated
using ((select auth.uid()) = user_id or public.is_css_vista_admin());

drop policy if exists "Students update their own profile" on public.student_profiles;
create policy "Students update their own profile"
on public.student_profiles for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Admins read administrator membership" on public.admin_users;
create policy "Admins read administrator membership"
on public.admin_users for select to authenticated
using (public.is_css_vista_admin());

drop policy if exists "Students read their own activity" on public.student_activity;
create policy "Students read their own activity"
on public.student_activity for select to authenticated
using ((select auth.uid()) = user_id or public.is_css_vista_admin());

drop policy if exists "Students create their own activity" on public.student_activity;
create policy "Students create their own activity"
on public.student_activity for insert to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Students read their own quiz attempts" on public.quiz_attempts;
create policy "Students read their own quiz attempts"
on public.quiz_attempts for select to authenticated
using ((select auth.uid()) = user_id or public.is_css_vista_admin());

drop policy if exists "Students create their own quiz attempts" on public.quiz_attempts;
create policy "Students create their own quiz attempts"
on public.quiz_attempts for insert to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Students update their own quiz attempts" on public.quiz_attempts;
create policy "Students update their own quiz attempts"
on public.quiz_attempts for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Admins read all progress" on public.student_progress;
create policy "Admins read all progress"
on public.student_progress for select to authenticated
using (public.is_css_vista_admin());

revoke all on table public.student_profiles from anon;
revoke all on table public.admin_users from anon, authenticated;
revoke all on table public.student_activity from anon;
revoke all on table public.quiz_attempts from anon;

grant select, update on table public.student_profiles to authenticated;
grant select, insert on table public.student_activity to authenticated;
grant select, insert, update on table public.quiz_attempts to authenticated;
grant usage, select on sequence public.student_activity_id_seq to authenticated;
grant usage, select on sequence public.quiz_attempts_id_seq to authenticated;

-- Add the first owner only after that person has created an account:
-- insert into public.admin_users (user_id)
-- select id from auth.users where email = 'owner@example.com';
