-- CSS Vista cloud content management and owner-only student directory.
-- Run after 202607300001_student_records_and_admins.sql.

create table if not exists public.site_content (
  id text primary key,
  content jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null,
  constraint site_content_singleton check (id = 'published')
);

create table if not exists public.site_content_versions (
  id bigint generated by default as identity primary key,
  content jsonb not null,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

alter table public.site_content enable row level security;
alter table public.site_content_versions enable row level security;

drop policy if exists "Everyone reads published site content" on public.site_content;
create policy "Everyone reads published site content"
on public.site_content for select
using (id = 'published');

drop policy if exists "Admins insert published site content" on public.site_content;
create policy "Admins insert published site content"
on public.site_content for insert to authenticated
with check (id = 'published' and public.is_css_vista_admin());

drop policy if exists "Admins update published site content" on public.site_content;
create policy "Admins update published site content"
on public.site_content for update to authenticated
using (id = 'published' and public.is_css_vista_admin())
with check (id = 'published' and public.is_css_vista_admin());

drop policy if exists "Admins read site content versions" on public.site_content_versions;
create policy "Admins read site content versions"
on public.site_content_versions for select to authenticated
using (public.is_css_vista_admin());

drop policy if exists "Admins create site content versions" on public.site_content_versions;
create policy "Admins create site content versions"
on public.site_content_versions for insert to authenticated
with check (public.is_css_vista_admin());

revoke all on table public.site_content from anon, authenticated;
revoke all on table public.site_content_versions from anon, authenticated;
grant select on table public.site_content to anon, authenticated;
grant insert, update on table public.site_content to authenticated;
grant select, insert on table public.site_content_versions to authenticated;
grant usage, select on sequence public.site_content_versions_id_seq to authenticated;

insert into public.site_content (id, content)
values ('published', '{}'::jsonb)
on conflict (id) do nothing;

create or replace function public.publish_css_vista_content(next_content jsonb)
returns timestamptz
language plpgsql
security definer
set search_path = public
as $$
declare
  published_at timestamptz := now();
begin
  if not public.is_css_vista_admin() then
    raise exception 'Administrator access required';
  end if;

  if next_content is null or jsonb_typeof(next_content) <> 'object' then
    raise exception 'Site content must be a JSON object';
  end if;

  insert into public.site_content_versions (content, created_by)
  select content, auth.uid()
  from public.site_content
  where id = 'published'
    and content <> '{}'::jsonb;

  insert into public.site_content (id, content, updated_at, updated_by)
  values ('published', next_content, published_at, auth.uid())
  on conflict (id) do update
  set content = excluded.content,
      updated_at = excluded.updated_at,
      updated_by = excluded.updated_by;

  -- Keep the latest 30 automatic restore points.
  delete from public.site_content_versions
  where id in (
    select id
    from public.site_content_versions
    order by created_at desc
    offset 30
  );

  return published_at;
end;
$$;

revoke all on function public.publish_css_vista_content(jsonb) from public;
grant execute on function public.publish_css_vista_content(jsonb) to authenticated;

create or replace function public.admin_student_directory()
returns table (
  user_id uuid,
  email text,
  display_name text,
  created_at timestamptz,
  last_sign_in_at timestamptz,
  last_seen_at timestamptz,
  progress_updated_at timestamptz,
  activity_count bigint,
  quiz_attempt_count bigint
)
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if not public.is_css_vista_admin() then
    raise exception 'Administrator access required';
  end if;

  return query
  select
    u.id,
    u.email::text,
    coalesce(p.display_name, ''),
    u.created_at,
    u.last_sign_in_at,
    p.last_seen_at,
    sp.updated_at,
    (select count(*) from public.student_activity a where a.user_id = u.id),
    (select count(*) from public.quiz_attempts q where q.user_id = u.id)
  from auth.users u
  left join public.student_profiles p on p.user_id = u.id
  left join public.student_progress sp on sp.user_id = u.id
  order by coalesce(p.last_seen_at, u.last_sign_in_at, u.created_at) desc;
end;
$$;

revoke all on function public.admin_student_directory() from public;
grant execute on function public.admin_student_directory() to authenticated;

